### ISSUE TITLE
Fix Security Issue with MPI_Info_get by introducing two replacement functions MPI_Info_get_string and MPI_Info_get_buflen

### ISSUE THREAD

**Issue by regrant** [mpi-forum/mpi-issues#133]
# Problem

Info Keys returned value length in C is always one less than the integer number of bytes needed for the buffer as it does not include the null terminator.

This leads to the following code resulting in a a non-terminated string in C:

```c
char* value;
ret = MPI_Info_get_valuelen(info, &key, &valuelen, &flag);
value = malloc(valuelen);
MPI_Info_get(info, &key, valuelen, value, &flag);
```

Code to do what is typically expected in common coding practice (null terminated) is as follows:

```c
char* value;
ret = MPI_Info_get_valuelen(info, &key, &valuelen, &flag);
value = malloc(valuelen+1);
MPI_Info_get(info, &key, valuelen, value, &flag);
```

Not having a null terminated string can result in many unwanted behaviours. The currently returned value will not result in the correct length to a call to strlen as required by C99.

Our current info string support makes it easy for users to accidentally under provision the memory needed for a value and thereby truncate the null terminator from the string accidentally. This is considered a major issue for security in C, and is non-compliant with current secure coding C standards like the SEI Cert C Coding Standard 

# Proposal

1. Add a new function MPI_Info_get_buflen that returns the length of buflen to equal that of the string plus the null terminator in C. This will make coding more intuitive and avoid unintended security violations.

2. Add a new function to replace MPI_Info_get that returns a string that is always guaranteed to have a null terminator in C. This new function takes the output of MPI_Info_get_buflen as the input length argument.

# Changes to the Text

Add to Chapter 9 MPI_Info_get_string and MPI_Info_get_buflen calls that include null terminators in C. 

# Impact on Implementations

Implementations will have to provide two new functions that return a value 1 greater than they currently return in legacy functions. This should have trivial impact on implementations. This only impacts C implementations.

# Impact on Users

New C code should be updated to reflect the new functionality. Existing code should be updated, but a trial search and replace will only result in a single byte of memory wasted for each info value retained in memory. Only C code is impacted by this change.

# References

[SEI C Cert link](https://wiki.sei.cmu.edu/confluence/display/c/STR32-C.+Do+not+pass+a+non-null-terminated+character+sequence+to+a+library+function+that+expects+a+string) (SEI C Cert Standard on non-null terminated strings)
Pull request: https://github.com/mpi-forum/mpi-standard/pull/128

Minor updates from Zurich can be found in commit: https://github.com/mpi-forum/mpi-standard/pull/128/commits/fd110d4aed2d25daa769ce134053ddfc6eaa4460 

PDF: [misc-2-buflen.pdf](https://github.com/mpi-forum/mpi-issues/files/3956523/misc-2-buflen.pdf)

**Comment by RolfRabenseifner** [comment]
This is definitely a non-backward compatible proposal without any real need.
If this problem exist, then your example may help.
My recommendation is:
- Change the sequence of definitions:
    - first MPI_INFO_GET_VALUELEN
    - second MPI_INFO_GET
- and at the end of MPI_INFO_GET your example in C ***AND*** Fortran.
  Fortran is needed, because it is without this +1 and therefore having only the example in C may result in wrong Fortran usage.
Please be aware, that your proposal should be written (at least as such issue text) before the two week deadline (May 14 noon) before the meeting, which starts May 28 noon, if it should be read this meeting, which may be the final or nearly final for new reading for MPI-4.0. Better would be full mpi-report.pdf
with clear highlighting of the change (e.g., manually added changebar) and pull request. I would support such an example-proposal - it is at least better than the current nearly empty page 370.

**Comment by regrant** [comment]
@RolfRabenseifner I've updated the ticket with more information. Not fixing this will make for code that is very easy to inadvertently write non-compliant C11 code with a moderately severe security issue. As far as I understand it, Fortran does not have this vulnerability. The proposed change will only impact the sections of text that already read "In C, ...".

The change could be considered backwards compatible in that old codes will still work as intended, they only end up wasting a byte of memory for their value string buffers. This won't break any existing codes that are properly coded with a +1 on the string buffer size.

Your suggestion is a good one about the sequence of VALUELEN and INFO_GET, I will include that in the pull request.

**Comment by hjelmn** [comment]
I agree with @regrant. This is a bug in the standard and it should be fixed.

**Comment by jeffhammond** [comment]
Hard pass on changing this semantic. Your example shows the trivial solution.

**Comment by hjelmn** [comment]
@jeffhammond The semantics do not match the language of the binding (C) and should be fixed. It looks like fortran leakage into the C bindings.

**Comment by omor1** [comment]
Currently documentation for `MPI_INFO_GET_VALUELEN` is:

>Retrieves the length of the value associated with `key`. If key is defined, `valuelen` is set to the length of its associated value and `flag` is set to true. If `key` is not defined, `valuelen` is not touched and `flag` is set to false. The length returned in C does not include the end-of-string character.

This is similar to the behavior of `strlen` in C (C11, N1570, §7.24.6.3):

>The `strlen` function returns the number of characters that precede the terminating null character.

It may be beneficial for users to state that the behavior of `MPI_INFO_GET_VALUELEN` is similar, but I don't think that changing the behavior is necessary. It certainly would be a bad idea for the C and Fortran bindings to have different, incompatible behavior.

**Comment by regrant** [comment]
@jeffhammond while I agree that the proper usage of the function can be realized with a +1 in the malloc, the first example is completely reasonable code for anyone quickly looking at the standard and trying to use this function (for example, MPICH doesn't mention this +1 behaviour in the docs [http://www.mpich.org/static/docs/v3.1/www3/MPI_Info_get_valuelen.html](url)) 

Writing what looks to be reasonable code from any other API/coding practice and accidentally creating a security issue with a non null-terminated string is bad. Also, the returned string from the standard practice coding example (#1) is not C11 compliant as there's no null-terminator, making it not work with any stdlib string functions.

@omor1  C11 recognized the behavior that we currently have with MPI_Info_get_valuelen as security problematic in calls like strlen() and replaced strlen() with strlen_s() (safe string length). MPI should match C standard best practice for security in my opinion.

**Comment by hjelmn** [comment]
@omor1 To add to that. String handling is fundamental different in C and Fortran. There are already MPI functions that have incompatible behavior between Fortran and C. Any function taking a string for example.

**Comment by omor1** [comment]
@regrant Annex K is option and not implemented in most standard libraries. Correspondingly, there has been very little use of the functions in any production codebases. In fact, there has been a proposal that Annex K be deprecated in C2x. (There is also a proposal to add `strnlen` with behavior nearly identical to `strnlen_s` to the standard library proper.) Any any case, the length returned by `strlen`, `strnlen_s`, and the proposed `strnlen` never includes the null terminator.

@hjelmn I suppose that is the case. My point still stands though: the behavior of the function is the same as that of the C library string length functions and should not confuse users. Actually, I would argue that it is the behavior of `MPI_INFO_GET` that is inconsistent; the provided length should be the length of the buffer, not the length of the string. It should, however, like the non-standard `strlcpy` (but unlike `strncpy`) ensure that the string is NUL terminated.

**Comment by regrant** [comment]
@omor1 My point was not about the function itself, it was about the dangers of non null-terminated strings. I agree that no one really implements strlen_s. However, the purpose of the srtlen calls in C really are different than the one that we're assigning to get_valuelen in MPI. 

The main use of the get_valuelen call is going to be so that the user can allocate a buffer before calling MPI_Info_get. Therefore, I'm proposing that that is what the user should get when they call get_valuelen, while keeping backwards compatibility by still making it a count of the chars in a string as a necessary compromise. Don't you find the inclusion of the len+1 in your bufsize call somewhat unintuitive in this case? Many of our apps people are C++ folks and only write C for MPI, and that's not intuitive for them as C++ doesn't null terminate strings. Given that a non null-terminated string is considered a fairly high severity security issue wouldn't this be preferable?

```
int len;
int flag;
MPI_Info_get_valuelen(info, key, &len, &flag);
if (!flag)
    /* do error */
int bufsize = len;
char *value = malloc(sizeof(char) * bufsize);
MPI_Info_get(info, key, bufsize, value, &flag);
if (!flag)
    /* do error*/
```

Given of course that you don't really need bufsize anymore, but I left it in there for context.

There's no use case that I can see for wanting the number of characters in a string inside the MPI library when you can't see the string without a get call. What you really want this function for is finding the size of the buffer so that you can get the string, then you can run strnlen on it after the get call. I can see an argument for having a function to return the length of the string in bytes including the null terminator as well. I think we agree on this. However, with this change in semantics we fill in a potential pitfall while remaining backwards compatible.

I'd like to try to prevent users from running into unintended non null-terminated strings if possible and the downside of changing these semantics is a trivial amount of memory wasted for legacy code.

Note that the tools chapter handles strings differently, see Section 14.3.3. They always guarantee that truncated strings end in a null terminator. That was my intention for the changes to the MPI_Info_get function. I'll have specification text soon to aid the discussion. If we fix MPI_Info_Get to always null terminate the returned string the valuelen change is not as important.

**Comment by RolfRabenseifner** [comment]
> The change could be considered backwards compatible in that old codes will still
> work as intended, they only end up wasting a byte of memory for their value
> string buffers. This won't break any existing codes that are properly coded
> with a +1 on the string buffer size.

No, it is not backward compatible, because returning "VALXXX" as value
and telling in the past that these are 6 characters and now changing it 
to that it counts with 7 characters is not backward compatible.
If you write for example stubs serving another language YYY,
such stubs must convert the 6 characters into 6 characters within 
the language YYY, and not 7 characters.

For example, if you copy several strings together to form
"KEY1=VALUE1,ZZZZ/KEY2=VALUE2,..."
then this string is definitely different to
KEY1=VALUE1\0,ZZZZ/KEY=VALUE2\0,..."
or even worse:
KEY1=VALUE1\u,KEY=VALUE2\u,..."
with \u representing an undefined character,
because the application software calculated the 
locations in the resulting string and used sting-copy-functions
to copy the "VALUE1" and "VALUE2" into these 7-character-slots.

In other words, to say that your proposal is backward compatible,
is wrong. There exist a class of applications, for which
this non-backward-compatible Change does not require any changes,
but this does not imply that this is true for all applications.

Nobody had the idea to modify strlen(), they always do this with
new routine names.
But, this is not important enough to deprecate the existing MPI routine,
with all the cost-intensive implications for existing applications,
because this problem can be resolved with two examples, one in C
and the other in Fortran. 

Best regards
Rolf

----- Original Message -----
> From: "github notifications" <notifications@github.com>
> To: "mpi-forum" <mpi-issues@noreply.github.com>
> Cc: "Rolf Rabenseifner" <rabenseifner@hlrs.de>, "Mention" <mention@noreply.github.com>
> Sent: Saturday, May 11, 2019 3:36:32 PM
> Subject: Re: [mpi-forum/mpi-issues] Change Info Keys valuelen argument semantics (#133)

> @RolfRabenseifner I've updated the ticket with more information. Not fixing this
> will make for code that is very easy to inadvertently write non-compliant C11
> code with a moderately severe security issue. As far as I understand it,
> Fortran does not have this vulnerability. The proposed change will only impact
> the sections of text that already read "In C, ...".
> 
> The change could be considered backwards compatible in that old codes will still
> work as intended, they only end up wasting a byte of memory for their value
> string buffers. This won't break any existing codes that are properly coded
> with a +1 on the string buffer size.
> 
> Your suggestion is a good one about the sequence of VALUELEN and INFO_GET, I
> will include that in the pull request.
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mpi-forum/mpi-issues/issues/133#issuecomment-491511743

-- 
Dr. Rolf Rabenseifner . . . . . . . . . .. email rabenseifner@hlrs.de .
High Performance Computing Center (HLRS) . phone ++49(0)711/685-65530 .
University of Stuttgart . . . . . . . . .. fax ++49(0)711 / 685-65832 .
Head of Dpmt Parallel Computing . . . www.hlrs.de/people/rabenseifner .
Nobelstr. 19, D-70550 Stuttgart, Germany . . . . (Office: Room 1.307) .

**Comment by regrant** [comment]
@RolfRabenseifner The reason that I'm saying that this backwards compatible is that the string handling in C that would be used in the stubs to aid in copying the data together. So converting a String to another language, the C string functions would look at the String and automatically terminate when you reach the null terminator. They should adapt to the correct length of the String, even if there's an allocated byte after the null terminator for that String.

Now if you've created your own implementation to copy all of the chars in a string (like using memcpy) and don't ever check the length and null-termination of the value returned by MPI, I'd argue that your code is already non-secure and should be corrected.

So to follow your example, if I was copying in many keys and values into a single String from C, I'd do this:

```
cur_len = 0;
len=strnlen(mpi_info_1,max_length);
strncpy(mpi_big_buffer, mpi_info_1, len);
cur_len = total_len + strnlen(mpi_info_1,max_length);
len=strnlen(mpi_info_2,max_length);
strncpy(mpi_big_buffer+(cur_len*sizeof(char)),mpi_info2,len);
```

Of course you should check that the Strings are null terminated for safety's sake since MPI doesn't guarantee that the returned value String is null terminated. I haven't done that here just for brevity.

But this will work regardless of the length returned from MPI as the string handling functions in C look for null terminators, not absolute lengths.

What actually happens for old code is that it allocates a buffer of +1 size than needed, so inside the String allocated memory you'd have VALUE\0\u but since the String functions ignore data after the \0 null terminator, your code would still work.

**Comment by omor1** [comment]
@regrant there is the possibility of a user relying on the returned length for something other than memory allocation.

```C
int len;
int flag;
MPI_Info_get_valuelen(info, key, &len, &flag);
char *value = malloc(sizeof(char[len+1]));
MPI_Info_get(info, key, value, &flag);

for (int i = 0; i < len; i++) {
    // do something with value[I]
}
```

Now, this is terrible for a number of reasons, but nothing stops a user from writing this sort of code. Here, changing the behavior of `MPI_Info_get_valuelen` could lead to crashes or incorrect behavior.

**Comment by regrant** [comment]
@omor1 and @RolfRabenseifner I agree that it's possible to write code that is backwards incompatible. Let me refine my language: This change is effectively backwards compatible with code that is written to be string-handling safe.  This means that this change should not be a burden on the vast majority of users.

I've added a backwards incompatibility notice to the appendix in the specifications text proposal as there's technically an incompatibility here. However, this change should not impact most users as they should be checking for null terminators since MPI_Info_get does not guarantee that the returned string will be terminated. That's one of the main points in this proposal, stopping MPI from ever returning a string in C from Info that's not null terminated. It's in the text, I've updated the ticket text to also reflect this.

I posit that not fixing a potentially major security issue in MPI (Info_get should always null terminate strings) is worse than having some backwards incompatibility, especially when the change does not impact most users of the function.

**Comment by jdinan** [comment]
The is the moral equivalent of changing `strlen` because all you have is `strcpy`.  Can we instead consider adding `strncpy` equivalents for MPI routines that perform string copies (i.e. add buffer length argument)?  This will give protection against all buffer overruns, including the case you have identified here.  Backward compatibility for this approach is also a non-issue.

**Comment by hzhou** [comment]
First, do we have the concensus that the following code is non-intuitive, the trap of missing the NULL terminator is a real issue?
```
char* value;
ret = MPI_Info_get_valuelen(info, &key, &valuelen, &flag);
value = malloc(valuelen+1);
MPI_Info_get(info, &key, valuelen, value, &flag);
```

Now, the issue seems merely to be the understanding of what is `valuelen`. The text that `valuelen` does not include end-of-string character is the culprit. To me, `valuelen` is the necessary buffer length that can hold the value, which includes necessary meta-data for the language. For C, that includes the NULL-terminator. For some other language binding, it has to account for whatever string metadata that language binding requires, which could be more than 1.

Question: if we simply modify the text to say the `valuelen` is the minimum buffer size that needed to hold the value, does it break backward compatibility?

**Comment by wesbland** [comment]
This failed the first vote in Albuquerque, New Mexico on 2019-12-12.

**Comment by regrant** [comment]
ticket 146 was the chosen solution for this issue.
