### ISSUE TITLE
Add MPI_ERR_PROC_ABORTED

### ISSUE THREAD

**Issue by abouteiller** [mpi-forum/mpi-issues#134]
# Problem

After a process is terminated by MPI_ABORT, other processes may still try to communicate with it, and need to report an appropriate error code.

# Proposal

The proposal adds the MPI_ERR_PROC_ABORTED error class, that can be returned by operations that fail due to an aborted process. 

# Changes to the Text

Section 8.4 on page 375.
The error class MPI_ERR_PROC_ABORTED has been added.

https://github.com/mpi-forum/mpi-standard/pull/112

# Impact on Implementations

Implementation need to add the new error class to their constant. 
Implementations are not forced to return  MPI_ERR_PROC_ABORTED or to support the partial abort semantic, which remains optional.

# Impact on Users

Fault and error tolerant codes can be written in a better way.

# References

Issue #3

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Does this new error class imply only that one of the MPI processes involved in the current MPI procedure call was previously aborted using MPI_ABORT? Alternatively, would/could this error class also be used if the MPI process had terminated (normally or abnormally) for some other reason? If the error class indicates the more general case (that the "other" MPI process has terminated, possibly due to MPI_ABORT but possibly due to some other situation/action), then this error class should be named appropriately, i.e. MPI_ERR_PROC_TERMINATED.

**Comment by abouteiller** [comment]
It does intend that the process was aborted (either directly calling MPI_Abort, or being on a communicator on which some rank called MPI_Abort). 

We'll add other error classes for other failure modes.

**Comment by wesbland** [comment]
This passed the first vote in Zurich, Switzerland on 2019-09-07.

**Comment by wesbland** [comment]
This passed the final vote in Albuquerque, New Mexico on 2019-12-12.

**Comment by abouteiller** [comment]
The PR has been merged to target branches mpi3.x and mpi4.x. We are done.
