### ISSUE TITLE
Partitioned Point-to-Point Communication

### ISSUE THREAD

**Issue by regrant** [mpi-forum/mpi-issues#136]
# Problem

MPI currently provides all multi-threaded functionality through the existing interface that was designed primarily for single-threaded operation. There are no interfaces designed specifically to address the unique requirements of multi-threaded communication in MPI. 

# Proposal

Partitioned communication modes extend the behavior of persistent point-to-point communication using a non-local initialization call. Partitioned communication is "Partitioned" because it allows for multiple contributions of data to be made from potentially multiple threads/tasks to a single communication operation. 

# Changes to the Text

A new chapter that fully describes partitioned communication.

# Impact on Implementations

Implementations would have to support a new set of function calls. While there is significant overlap with persistent communications, the initialization phase of partitioned communication requires implementation work. Significant optimizations are also available for partitioned communication inside of implementations.

A prototype library exists that works with all implementations, making initial support for partitioned communication easy to integrate on a functional level.

# Impact on Users

Users will have a new interface to use for point to point communication that is designed for multi-threading. As this is a new interface, no existing code will be impacted.

# References

Pull request: https://github.com/mpi-forum/mpi-standard/pull/117

**PDF for Portland Meeting:**
[part.pdf](https://github.com/mpi-forum/mpi-issues/files/4153762/part.pdf)

**PDFs for December Albuquerque Meeting:**

PDF to be read: [part.pdf](https://github.com/mpi-forum/mpi-issues/files/3888150/part.pdf)

PDF of differences since October 30th Virtual Meeting: 
[part_comm_diff_virtual_oct_2019.pdf](https://github.com/mpi-forum/mpi-issues/files/3888142/part_comm_diff_virtual_oct_2019.pdf)

PDF of all Differences to December meeting from Zurich Meeting:
[part_comm_diff_zurich.pdf](https://github.com/mpi-forum/mpi-issues/files/3888145/part_comm_diff_zurich.pdf)

**PDFs for Virtual Meeting:**
PDF of work in progress resolving issues found in the Oct 30th Virtual Meeting:
[part.pdf](https://github.com/mpi-forum/mpi-issues/files/3798714/part.pdf)

PDF from October 30th 2019 Virtual Meeting:
[part.pdf](https://github.com/mpi-forum/mpi-issues/files/3794625/part.pdf)

PDF Read during plenary: [part.pdf](https://github.com/mpi-forum/mpi-issues/files/3237690/part.pdf)

PDF Changes from last physical meeting reading: 
[part_diff_from_chicago.pdf](https://github.com/mpi-forum/mpi-issues/files/3548012/part_diff_from_chicago.pdf)

PDF Changes from Virtual Meeting #1 : 
[part_diff_from_virtual.pdf](https://github.com/mpi-forum/mpi-issues/files/3547979/part_diff_from_virtual.pdf)

**Comment by jeffhammond** [comment]
Why not endpoints?

**Comment by hjelmn** [comment]
@jeffhammond I will let @regrant explain this PR. I have seen the data and I generally support this PR. Also, I plan to introduce a concept for RMA that will effectively make endpoints unnecessary for RMA. Effectively I can show that hiding endpoints inside the implementation (not exposing them ala SHMEM) provides performance on-par (or better) than endpoints. I will submit my PR soon.

**Comment by hjelmn** [comment]
And let's face it. Endpoints is effectively dead unless someone plans to revive the effort.

**Comment by pavanbalaji** [comment]
The endpoints proposal was suspended because we pointed out at the F2F meeting that we can achieve the same performance by hiding the same concept inside the MPI implementation.  I owe the Forum a more detailed presentation/analysis on it.  We have been continuing work along those lines and our findings match our initial thought, except for some cases where the user communication pattern is hard to predict for the MPI implementation.  I'll present more details soon.

**Comment by sayantansur** [comment]
Agree with @pavanbalaji on this. The hints to allow overtaking messages and no any source significantly improved potential concurrency in MPI's usage of the fabric. Although I haven't (yet) seen any data on an MPI implementation exploiting it (could be I am not aware of what may have been published).

**Comment by hjelmn** [comment]
@sayantansur We have looked at the performance of the allow overtaking info key. Results are under submission.

**Comment by jeffhammond** [comment]
@hjelmn @regrant 
>  I have seen the data.

Show me the data.

@hjelmn
> Endpoints is effectively dead unless someone plans to revive the effort.

So what you are saying is that, because no one wants to put in the effort on endpoints, we should put effort into evaluating this completely new proposal that solves the same problem?  This is not a good argument.

**Comment by regrant** [comment]
@jeffhammond happy to. Here's a link to the latest [paper](https://www.researchgate.net/publication/333628811_Finepoints_Partitioned_Multithreaded_MPI_Communication)

the tldr:
Unlike endpoints, partitioned communication doesn't increase the number of MPI-level messages that need to be processsed/matched, it's the same overheads as current thread_single code. Also, it allows for very low overhead multi-threading, among other side benefits.

If you're interested in why this matters, I covered some of it in the virtual meeting on April 17th. There's also some academic motivation [here](https://www.researchgate.net/publication/326728934_Measuring_Multithreaded_Message_Matching_Misery)

**Comment by jeffhammond** [comment]
@regrant 
> Unlike endpoints, partitioned communication doesn't increase the number of MPI-level messages that need to be processed/matched...

Please explain this to me.  In the usage model with which I am familiar, endpoints takes a code written for `MPI_THREAD_MULTIPLE` and allows the exact same set of messages to complete faster by eliminating a bunch of mutex overhead.

**Comment by regrant** [comment]
@jeffhammond You're correct on the send side regarding overheads, it's the receive side that really benefits from this. There's some subtlety in how the send side works with partitioning that _may_ allow us to optimize it more than endpoints. For a review of the receive side issues and some brief discussion of the underlying causes you'll probably want to read the second paper I linked to [above](https://www.researchgate.net/publication/326728934_Measuring_Multithreaded_Message_Matching_Misery)

**Comment by jdinan** [comment]
#### High level comments:

* The proposal now assumes that partitions are all exactly the same size and that the buffer can be described by count * datatype.  This captures a subset of regular data layouts.  For example, it does not capture arbitrary subarrays and also does not work for situations where the count is not evenly divisible by the number of partitions (i.e. threads).  Are we thinking about a version of this API that takes an array of length number of partitions for count and datatype?

* What are the threading semantics of MPI_Pready?  IIUC, this routine may be callable in an accelerator context in some MPI implementations.  Does is need special threading semantics to make this work?

* I see that psend has to match precv now.  Does this mean that if the receiver posts a receive that would match a given psend that the non-paritioned recv will not match the psend?  Or does it mean that the receiver cannot post a non-paritioned recv if it would match a psend?

* The text has improved, but I think more work is needed to refine the text so that is precise enough for inclusion in the MPI standard.

* Still concerned that the OpenMP examples make assumptions about exactly how many threads will be there at runtime.  They will deadlock if the number of threads is not the same as the number of partitions.  We should raise awareness of this somehow in the examples.  For example, with a check that aborts if the example would deadlock.

#### A few specific comments on part_diff_from_chicago.pdf:

pg. 85, l. 25-33: Instead of this advice to users, can we append the citations to the first paragraph: "Partitioned communication modes [26, 27] ..."  I don' t think it's necessary to discuss the naming difference between prior publications and standardization.

pg. 85, l. 40: "between two points" -> "between two MPI processes"?

pg. 85, l. 42: I am hesitant to introduce more usage of "full/half channel" into the specification given that the term is not well defined.  Can we simplify these two sentences to, "First, partitioned communication initialization can perform all steps required to enable data transfer between two MPI processes, including matching and buffer setup."

pg. 86, l. 3-5: Delete this paragraph, it doesn't say anything.

pg. 86, l. 6-9: This paragraph nearly says nothing.  Whatever meaningful statement is here should be incorporated into the subsequent text.

Reading further, I think this section (4.2) should be reorganized.  There is still a good amount of verbiage in here that reads like motivating text for the Forum (e.g. persistent communication semantics are ideal for partitioned communication), but is superfluous in a specification.  For example, the section could instead open with "Partitioned communication operations are initiated using the MPI_Psend_init and MPI_Precv_init routines.  Similar to persistent operations, the partitioned initialization routines perform setup for future communications and return MPI_Request objects that can be used to reference a given operation.  In contrast with persistent operations, partitioned communication initialization operations are non-local, ..."

I would be happy to help with edits, but I think a PR would be much more efficient than posting feedback here...

**Comment by RolfRabenseifner** [comment]
Here my review based on all the discussions during the reading at the Zürich Forum meeting 9/2019:
[136_review_byRolf.txt](https://github.com/mpi-forum/mpi-issues/files/3587878/136_review_byRolf.txt)

**Comment by tonyskjellum** [comment]
Reread discussion: remove the word 'existing'

Note we renamed an API given feedback: MPI_PTEST -> MPI_PARRIVED; no action item.

partition value -> partitions in MPI_Psend_init()  plus others.

Circa lines 455-503 of diff.
int *provided  -> int provided
provided -> &provided

and there are repetitions of this error.

line 676 of diff -- missing }

Make sure MPI_Init_thread is checked in all examples (provided).

Examples are not in the example environment.  Correct LaTeX.

Line 441 of diff has a pageref{} -- get rid of it.

**Comment by tonyskjellum** [comment]
Straw poll N-1 yes for accepting tomorrow, 1 abstain planned.

**Comment by wesbland** [comment]
This passed the no-no vote in Albuquerque, New Mexico on 2019-12-12.

**Comment by tonyskjellum** [comment]
A new PDF will be added soon.  And attached below.

**Comment by wesbland** [comment]
This proposal passed a first vote at the February 2020 meeting:

Yes - 18
No - 2
Abstain - 4

**Comment by tonyskjellum** [comment]
For second vote, editorial changes only have been made since Portland

PR: https://github.com/mpi-forum/mpi-standard/pull/117

PDF: https://github.com/mpi-forum/mpi-standard/files/4777385/mpi40-report-ticket136-14jun20.pdf

**Comment by wesbland** [comment]
This passed a second vote on 2020-06-30.

https://www.mpi-forum.org/meetings/2020/06/votes

**Comment by tonyskjellum** [comment]
Erratum... remove vestigial sentence fragment... see also PR.

[mpi40-report-ticket136-11jul20.pdf](https://github.com/mpi-forum/mpi-issues/files/4913679/mpi40-report-ticket136-11jul20.pdf)

**Comment by rkowalewski** [comment]
While reading through the [atest report](https://github.com/mpi-forum/mpi-issues/files/4913679/mpi40-report-ticket136-11jul20.pdf) I noticed some inconsistencies in Example 4.4, although I am not sure about this.

- Line 37, where the sender calls `MPI_Psend_init`: Each partition transmits `send_partlength` elements of type `send_type`, which specifies s contiguous buffer of `send_partlength * sizeof(MPI_DOUBLE)`. Hence we have `send_partlength * send_partlength * MPI_DOUBLE` elements. To fix it, we need to replace the count argument to 1:
~~~c
MPI_Psend_init(message, send_partitions, 1, send_type, dest, tag,
~~~

- Line 41: replace `partitions` with `send_partitions`.

Another comment, not related to this issue: Parsing the correct line numbers on the right hand side is very cumbersome, as font sizes differ too much. AFAIK, there are some discussions about style guides in a different issue. I would suggest larger line numbers and print them on the left.
