### ISSUE TITLE
Errata: fix an obvious parameter name error

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#149]
# Problem

Two parameters in the language-independent binding for MPI_UNPACK_EXTERNAL are incorrect:

````    
MPI_UNPACK_EXTERNAL(..., outsize, position)
````
    
# Proposal

These should be "outcount" and "datatype", respectively.  Making this change will make the names in the parameter listing be consistent with the explicit parameter listing in the language-independent binding, the C binding, and the Fortran bindings.

# Changes to the Text

```patch
diff --git a/chap-datatypes/datatypes.tex b/chap-datatypes/datatypes.tex
index d301f74..3d99828 100644
--- a/chap-datatypes/datatypes.tex
+++ b/chap-datatypes/datatypes.tex
@@ -3827,7 +3827,7 @@ packed with
 
 \mpicppemptybind{MPI::Datatype::Pack\_external(const~char*~datarep, const~void*~inbuf, int~incount, void*~outbuf, MPI::Aint~outsize, MPI::Aint\&~position) const}{void}
 
-\begin{funcdef}{MPI\_UNPACK\_EXTERNAL(datarep, inbuf, insize, position, outbuf, outsize, position)}
+\begin{funcdef}{MPI\_UNPACK\_EXTERNAL(datarep, inbuf, insize, position, outbuf, outcount, datatype)}
 \funcarg{\IN}{datarep}{data representation (string) }
 \funcarg{\IN}{inbuf}{input buffer start (choice) }
 \funcarg{\IN}{insize}{input buffer size, in bytes (integer) }
```

# Impact on Implementations

None.

# Impact on Users

None.

# References

* Associated PR for the mpi-3.x branch: https://github.com/mpi-forum/mpi-standard/pull/133
* Associated PR for the mpi-4.x branch: https://github.com/mpi-forum/mpi-standard/pull/134

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Procedurally, (I assert that) these typo fixes could be ticket-0/chapter-committee changes, i.e. never formally presented to the MPI Forum as an errata or anything else that requires a vote.

**Comment by RolfRabenseifner** [comment]
Yes, I agree in this case.
But I want to mention that in the case that there is a typo in an argument name in a Fortran binding, then this is not a simple typo, because it would be a non-backward compatible change, due to the fact that Fortran allows keyword-based argument lists, i.e., using formal_arg=actual_arg. Using this, the names of the formal arguments are binding.
Nevertheless, I would do such a change (if needed) as an errata as long that we expect a rare use of the routine multiplied with the rare use of keyword-based argument lists (which was added in MPI-3.0).
The risk with chapter committees is, that they may oversee exactly such Fortran issues.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@RolfRabenseifner neither of these typos are wrong in the Fortran bindings. In fact, *all* language-specific bindings have the correct names for these procedures. It is only the language-independent specification that has the problem. This is why I assert ticket-0 status - because this change only affects the text of the MPI Standard and will not (must not) affect any valid MPI library implementation or any valid MPI program.
