### ISSUE TITLE
Consistent use: Throughout - Fortran 2008 TS 29113 Formatting

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#163]
## Problem

What is the format for "Fortran 2008 TS 29113"? Is there a + (page 639 doesn't use one)? Is it F2008+TS 29113?

### Suggested Fix

Check with MPI Fortran committee

**Comment by wesbland** [comment]
Voting:
Editor change - 5
Chapter Committee - 2

**Comment by wgropp** [comment]
Which form is correct for Fortran?

**Comment by wesbland** [comment]
> Which form is correct for Fortran?

I guess we need to ask our resident Fortran experts? @hritzdorf / @jsquyres / @RolfRabenseifner 

My quick search didn't find any use of the `+`, but it also doesn't seem that the two are ever officially tied together. The TS stands apart. So to me, the better option would be to say:

> The Fortran MPI language bindings have been designed to be compatible with the Fortran 90 standard with additional features from Fortran 2003 and Fortran 2008 [40] **with** TS 29113 [41].

**Comment by RolfRabenseifner** [comment]
The "+" means "plus" or "together with". 
I found in MPI-3.1
 - 11 x "Fortran 2008 + TS 29113"
 -   1 x "Fortran 2008+TS 29113"
 -   4 x "Fortran 2008 TS 29113"
 - 34 x "TS 29113"
and once the long version
"The MPI Fortran bindings in the mpi_f08 module are designed based on the Fortran
2008 standard [40] together with the Technical Specication \TS 29113 Further Interoperability
with C" [41] of the ISO/IEC JTC1/SC22/WG5 (Fortran) working group."

My recommendation is to substitute the
 -   1 x "Fortran 2008+TS 29113"
 -   4 x "Fortran 2008 TS 29113"
by always
           "Fortran 2008 + TS 29113"
and then we are consistent.
There are locations where a long wording "Fortran 2008 together with TS 29113" would not fit the English of to the surrounding text whereas the mathamatical "+" works.

**Comment by wesbland** [comment]
Sounds like this needs more discussion and will need to move to MPI 4.1 since we're out of time for 4.0

**Comment by wgropp** [comment]
Agreed. This can wait, and I've changed the label

**Comment by wgropp** [comment]
MPI 4.1 is almost here. Outside of the MPI specification, I can find no use of + as in Fortran 2008 + TS 29113.  I like @wesbland  text for the first use, and then Fortran 2008 with TS 29113 uniformly throughout the standard.  Or we can wait until MPI 5.0.

**Comment by RolfRabenseifner** [comment]
TS 29113 was especially defined to allow the consistency of MPI with Fortran. Therefore it should be mainly referenced by the MPI standard.
Outside, one can find it in the status informations of Fortran compiler implementations.
"Fortran 2008 with TS 29113" is a good idea for a uniform wording in MPI-4.1.
One can also check whether "Fortran 2008 with TS 29113 or Fortran 2018 and later" would work at most locations.
It depends, whether a minimal requirement is defined, for example for "TYPE(*), DIMESION(..)", then Fortran 2008 with TS 29113 is correct. If the whole valid scope is meant, then it is "Fortran 2008 with TS 29113 or Fortran 2018 and later".

**Comment by jeffhammond** [comment]
We should now use Fortran 2018. That includes the relevant TSes and is a single document to reference. Using F08+TS was a necessary evil in MPI-3. It's no longer necessary or appropriate.

**Comment by RolfRabenseifner** [comment]
Please have a look at MPI-4.0 Section 19.1.6 MPI for Different Fortran Standard Versions.
It describes the minimal requirements that we have for which functionality of MPI. 
This minimal requirement normally does not change with newer releases of the Fortran standard.
Therefore, we can keep the text as it is

> _For Fortran 2008 + TS 29113 and later and
> For Fortran 2003 + TS 29113:_

or we can add Fortran 2018.
We do not use any other feature of Fortran that was added between F2008+TS29113 and F2018.

**Comment by wgropp** [comment]
I'd like to propose Rolf's solution above:

- In most places: Fortran 2008 with TS 29113 or Fortran 2018 and later
- In those places calling out the minimum required level o Fortran: Fortran 2008 with TS 29113

Thoughts?

**Comment by wesbland** [comment]
cc: @martinruefenacht

**Comment by jeffhammond** [comment]
We don't use all of any language specification. Fortran 2018 is the single reference for Fortran we require. What is the value in making multiple references, other than history? Put a historical note in the language bindings chapter if you want, but otherwise use Fortran 2018.

**Comment by RolfRabenseifner** [comment]
The MPI Forum required section 19.1.6 and it is good that we have it, It is not about historical. It is about whether an older compiler version is still okay for partial or full MPI Fortran support. 
You may be right with some location in the MPI standard. 
But for example the first location (in MPI-4.0 Sect. 2.5.5):

> _"with the Fortran mpi_f08 module, such arguments are declared with the Fortran 2008 + TS 29113 syntax TYPE(*), DIMENSION(..);"_

- Changing it into _"Fortran 2008 with TS 29113 or Fortran 2018 and later"_ is correct because you do not implicitly give the hint that Fortran 2018 compilers are required for mpi_f08.
- Just changing it into the short _"Fortran 2018"_ gives the completely wrong impression. Especially when comparing MPI-4.0 with MPI-4.1, one has the idea that there is a change in the requirement for mpi_f08.
- Just letting it as it is would be correct, but for those who have a Fortran 2018 compiler, it is an outdated reference.

Therefore, I hope that you can also agree with @wgropp's answer above

> I'd like to propose Rolf's solution above:
> 
> * In most places: Fortran 2008 with TS 29113 or Fortran 2018 and later
> * In those places calling out the minimum required level of Fortran: Fortran 2008 with TS 29113
> 
> Thoughts?

**Comment by jeffhammond** [comment]
We should specify the specific features of Fortran 2018 we require, which is not hard. I don't know why you want to use one huge and one short document to describe what fits into a bulleted list, with references to Fortran 2018 features.

**Comment by wgropp** [comment]
On further reflection, my preference is to define what we mean by "Fortran" and by "C" in the terms chapter, and then stick with just Fortran and C when mentioning languages.  We would explain the binding display (Fortran 2008) as being short for Fortran 2008 with TS29113 or Fortran 2018 or later. Only when something different is required should we get into details of the language version.  We are not writing a context-free document.

**Comment by wgropp** [comment]
In looking at the text more carefully, it is more complicated to fix this up.  There are many places that talk about "TS29113 language feature" or "as part of TS29113". This makes sense for the F2008 with TS29113 spec but not really for F2018. I still think that the best resolution is to define what "Fortran" means, and provide some background on the historical progress, as well as explaining the "08" in the mpi_f08 name.  Most of this would be in the bindings chapter. Some text needs to be rewritten to refer to the specific features, rather than assume that only TS29113 provides the needed capabilities, which is not really true for F2018, which integrates TS29113 as part of Fortran, rather than as a separate document.  For example, I would argue that F2018 does not provide TS29113 - rather, it provides a superset of features defined in TS29113. As Jeff said, I think it would be better to talk about specific features rather than one transient solution to the problem within Fortran 2008 (but not 2018).
