### ISSUE TITLE
Error: Section 13.4.1 - p. 535 - MPI_FILE_READ Equivalency

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#169]
## Problem

The MPI equivalents are MPI_FILE_READ ..." is *incorrect*. The MPI routines have different semantics than the POSIX routines.  Equivalent is the wrong term.

### Suggested Fix

Instead, "The MPI routines to read from and write to a file are …"

**Comment by wesbland** [comment]
This one is leaning toward chapter committee in the voting, but at least a couple of errata:

* Editor change - 1
* Chapter committee - 4
* Errata - 2

**Comment by schulzm** [comment]
Suggested change for the text (with some context around it):

POSIX read()/fread() and write()/fwrite() are blocking, noncollective operations
and use individual file pointers. The conceptual counterparts of these calls in MPI are MPI_FILE_READ and MPI_FILE_WRITE.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@schulzm "blocking" in your suggestion is used in a manner different to the definition in MPI.

You mean "will not return to user code until the data has been read from (or written to) the file, as per their definitions in the POSIX standard".

MPI means "is either related to an MPI operation and is non-local or is completing for some MPI operation".

Since these are not MPI functions (and not related to any MPI operations), the semantic term blocking does not make sense when applied to them in the context of the MPI Standard.

By "noncollective" you probably mean "not collective", although you should probably use "local" instead because you want to exclude all of non-local not just the collective part of that semantic. The terms "collective" and "non-local" also require the function to be related to an MPI operation. The term "local" does not require that and could be correctly used, except that we define all of these terms only as applicable to MPI functions/procedures.

We should not presume to describe the behaviour of non-MPI things in the MPI Standard, especially when there is another perfectly good standard that does that job for us.

**Comment by wgropp** [comment]
POSIX read and write are related to MPI_FILE_READ and MPI_FILE_WRITE in that they effect the movement of data from/to the open file. The detailed semantics are *very* different, particularly with respect to completion and visibility to other processes. Ignoring this fact is the problem that I have with the current statement in the standard.

**Comment by wgropp** [comment]
To be more specific, POSIX read/write have exceptionally strong consistency semantics, which make them very different from MPI file read and write, which have precise but much more relaxed (and useful) consistency semantics. Saying that the POSIX and MPI operations are essentially the same is not only false, it reinforces the false notion that the only important part of these operations is that they move data from/to a file.

**Comment by schulzm** [comment]
Discussion at the VM on 4/8 - decision to just remove these three lines from the text, PR coming next

**Comment by wesbland** [comment]
This passed an errata vote on 2020-08-19.

https://www.mpi-forum.org/meetings/2020/08/votes
