### ISSUE TITLE
Omission: p. 387 - Initialized Binding Fix

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#176]
## Problem

MPI_INITIALIZED needs (logical) for flag

### Suggested Fix

Suggest asking the bindings committee to review

**Comment by wesbland** [comment]
The voting here is mixed. We'll discuss how to resolve this during a virtual meeting.
* Editor - 1
* Chapter committee - 4
* Errata - 2

**Comment by wesbland** [comment]
This may already be done by Pythonization. @jsquyres @martinruefenacht

**Comment by wesbland** [comment]
The bindings committee ( @puribangalore ) and the environment management committee (@bosilca ) need to decide the solution and make an errata with the Pythonization folks to fix this in the Python scripts.

The chapter committee may decide that this is ticket 0.

**Comment by jsquyres** [comment]
Fixing this is a trivial change to the Pythonized binding (remember: the Pythonization effort sought parity with MPI-3.1, and this annotation was not in MPI-3.1).  Specifically: there is actually a `suppress` clause in the Pythonized binding for this function to make the LIS annotation _not_ appear because this annotation did not appear in MPI-3.1.  Fixing this issue simply means removing the `suppress` parameter in the Pythonized binding for this function.

Note that this is a chapter committee issue, not a Pythonization issue, because at the Albuquerque New Mexico 2019 meeting, the Forum was quite clear that it wanted Pythonization to make parity with MPI-3.1 -- it did *not* want Pythonization to silently change/"fix" LIS bindings (as compared to MPI-3.1).

My $0.02: this is a ticket 0 issue for the chapter committee once Pythonization is merged (https://github.com/mpi-forum/mpi-standard/pull/152).

**Comment by wesbland** [comment]
This is still labeled as an errata item. Was it decided that this will be chapter committee?

**Comment by wgropp** [comment]
I do not believe this should have an errata; I believe this is ticket 0.
