### ISSUE TITLE
Omission: p. 387 - Abort Binding Fix

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#177]
## Problem

MPI_ABORT needs the arg types (e.g., (handle))

### Suggested Fix

Suggest asking the bindings committee to review

**Comment by wesbland** [comment]
The voting here is mixed. We'll discuss how to resolve this during a virtual meeting.

* Editor - 1
* Chapter committee - 4
* Errata - 2

**Comment by wesbland** [comment]
The bindings committee ( @puribangalore ) and the environment management committee (@bosilca ) need to decide the solution and make an errata with the Pythonization folks to fix this in the Python scripts.

The chapter committee may decide that this is ticket 0.

**Comment by jsquyres** [comment]
Fixing this is a trivial change to the Pythonized binding (remember: the Pythonization effort sought parity with MPI-3.1, and this annotation was not in MPI-3.1).  Specifically: there is actually a `suppress` clause in the Pythonized binding for this function to make the LIS annotation _not_ appear because this annotation did not appear in MPI-3.1.  Fixing this issue simply means removing the `suppress` parameter in the Pythonized binding for this function.

Note that this is a chapter committee issue, not a Pythonization issue, because at the Albuquerque New Mexico 2019 meeting, the Forum was quite clear that it wanted Pythonization to make parity with MPI-3.1 -- it did *not* want Pythonization to silently change/"fix" LIS bindings (as compared to MPI-3.1).

My $0.02: this is a ticket 0 issue for the chapter committee once Pythonization is merged (https://github.com/mpi-forum/mpi-standard/pull/152).

**Comment by bosilca** [comment]
@jsquyres is right, the fix after the pythonization is merged is trivial. I'll keep track of this until we merge the python support.

```diff
diff --git a/chap-inquiry/inquiry.tex b/chap-inquiry/inquiry.tex
index e9bcede..cd3f091 100644
--- a/chap-inquiry/inquiry.tex
+++ b/chap-inquiry/inquiry.tex
@@ -1965,13 +1965,11 @@ Section~\ref{sec:ei-threads}.
         "comm",
         "COMMUNICATOR",
         desc="communicator of tasks to abort",
-        suppress="lis_paren",
     )
     parameter(
         "errorcode",
         "ERROR_CODE",
         desc="error code to return to invoking environment",
-        suppress="lis_paren",
     )
 \end{mpi-binding}
```

**Comment by jsquyres** [comment]
@bosilca Pythonization is in.  Feel free to PR this.  Thanks!

**Comment by wesbland** [comment]
This is still labeled as an errata item. Was it decided that this will be chapter committee?

**Comment by wgropp** [comment]
I don't know what the decision was, but I do not consider this an errata. That is mostly because I've become more sensitive to things losing value when they contain too much inconsequential material. I do not believe anyone is served by including as errata every minor fix to the text.

**Comment by wesbland** [comment]
I think what we've gone with procedurally is that there are things that we handle as errata (reading and single vote) because we want the forum to approve it to make sure it's correct and it's relatively small. However, these things are sometimes too minor to include in the errata document for the reason you just described.
