### ISSUE TITLE
Update: Section 11.8 - p. 496 - Example Style

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#211]
## Problem

Examples 11.20 looks different than other examples that show two (or more) processes (e.g., Example 11.18).  These should have the same style.

### Suggested Fix

Edit Example 11.18 to use "Process B…:" and add text to that example explaining the format: "In the following, "Process B…" means any other process besides process A, and is used where multiple processes may execute the code in that column."

**Comment by wesbland** [comment]
* Editor - 1
* Chapter committee - 5
* Errata - 1
* Full Proposal - 0

Either way, this goes to @wgropp.

**Comment by devreal** [comment]
I posted https://github.com/mpi-forum/mpi-standard/pull/180 to address this.

The example as it was was correct because it didn't scale to more than 2 processes. This has been addressed in the PR.

One thing I noticed is that text between examples is not separated from the previous example. Fir example, there is text between Example 11.17 and Example 11.18 but it is indistinguishable from the text of Example 11.17. That makes it easy to miss explanations there. Should this be addressed in a separate issue?
