### ISSUE TITLE
Update: Multiple occurances - Inter(-?)communicator

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#230]
## Problem

Is it inter-communicator or intercommunicator? (See section titles for 6.2.3, 6.2.4

### Suggested Fix

Use intercommunicator and (also intracommunicator)

**Comment by wesbland** [comment]
Probably an editor change. Let's decide as a group though.

* Editor - 4
* Chapter committee - 3
* Errata - 0
* Full Proposal - 0

**Comment by wesbland** [comment]
@mahermanns Raised a valid point that having the hyphen makes it easier to call out the difference between intra- and inter- given the small difference between the two.

In the document itself, we are very inconsistent and use both quite a bit.

The group agreed that the point about keeping the dash was a good one and we should keep the dash and we should change the document to use the dash everywhere.

**Comment by wesbland** [comment]
@martinruefenacht raised a good point that ideally this (and other similar decisions) would be enforced by a CI check to make sure we don't screw it up again.

**Comment by wgropp** [comment]
Agreed.  I can add this to the checks that already look for some common errors.

**Comment by wesbland** [comment]
@wgropp , @martinruefenacht may already have something in mind / development. I know he was adding things to the Azure Pipelines job for Pythonization. I think he might have been developing something here.

If there's already something built into the repository that we can add to that job, that'd be great.

**Comment by wgropp** [comment]
See the checklatex target in the Makefile.  This already looks for problems I've had to fix in the document, including some that aren't strictly improper LaTeX use, such as punctuation on the wrong side of a quote.

**Comment by martinruefenacht** [comment]
For the Pythonization tests we have a test suite written using pytest, which gets automatically found and executed by executing "pytest" in the root. The binding tool tests reside in "binding_tool/tests/test_*.py".

I think at this point it is just a choice of tool. Pytest does nicely integrate with Azure pipelines due to a pytest extension which just does it. Generating automagic xml output for azure for the UI feels:
[Azure](https://dev.azure.com/mpiforumbot/MPI%20Forum/_build/results?buildId=23&view=ms.vss-test-web.build-test-results-tab)

It also provides coverage metrics and many more things if we chose to go down that specific rabbit hole. (We can have a lot of fun...)

Personally I think Python is a better choice (obviously :D) the reason being that it is a more human readable language than Bash, etc. Also we can use the pytest integration to have fixtures and very many dynamic/awesome things. Another upside of pytest is we can write tests more modular.

**Comment by wgropp** [comment]
I'm fine with having someone else convert the existing tests to Python.

**Comment by martinruefenacht** [comment]
I have attempted an implementation of this:
[branch in fork](https://github.com/martinruefenacht/mpi-standard/tree/feat-python-ci)

Look at the "tests" directory. Everything should be executed via the azure pipeline or pytest in the root of the directory.
The conftest.py provides a fixture to load all latex files. The test_word.py contains the test which
checks whether "intracommunicator" or "intercommunicator" are used.

Let me know if you are happy with this, if so I will create a PR/issue as infrastructure for the document.

This does not modify the text. For the moment I have left that up to Bill since he is the assignee.

**Comment by wgropp** [comment]
I'm not sure how to test this.  It looks ok, but how can I run it to check (there should be a Makefile target). Similar to "make checklatex", authors should be able to run this to check their updates.

**Comment by martinruefenacht** [comment]
This would be run automatically when pushed to the git repository (already in place). If we want to manually test it, then a make target which calls pytest would work fine. This requires python3.7 to be installed. We can fetch all the other dependencies when required (pytest, pytest-cov, hypothesis).

**Comment by wgropp** [comment]
I strongly believe that manual testing is necessary - authors (or at least the editor) should be able to easily run the tests.  The automatic tests are a good backup check.

**Comment by wgropp** [comment]
Oh, and I don't have pytest installed, so IIUC, I can't run these tests.

**Comment by jsquyres** [comment]
Is there a problem with installing pytest?

**Comment by wgropp** [comment]
I'm not a python user (yet), and yes, after searching for pytest and following the install directions, the install reported some errors. I don't know whether they are important or not, though they look like hard failures.

**Comment by wgropp** [comment]
`Building wheels for collected packages: scandir
  Running setup.py bdist_wheel for scandir ... done
  Stored in directory: /Users/gropp/Library/Caches/pip/wheels/91/95/75/19c98a91239878abbc7c59970abd3b4e0438a7dd5b61778335
Successfully built scandir
matplotlib 1.3.1 requires nose, which is not installed.
matplotlib 1.3.1 requires tornado, which is not installed.
Installing collected packages: configparser, contextlib2, scandir, pathlib2, zipp, importlib-metadata, funcsigs, wcwidth, atomicwrites, pluggy, py, attrs, more-itertools, pyparsing, packaging, pytest
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/configparser.pyc'
Consider using the `--user` option or check the permissions.

You are using pip version 18.0, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
gropp@wdg-macbook mpi-standard %`

**Comment by wgropp** [comment]
(Gah - I tried to insert code, but it discarded line breaks. Next time, I'll take a screen shot :( )

**Comment by wesbland** [comment]
Use triple backticks when adding multiple lines.

**Comment by jsquyres** [comment]
You can use ``` to start/stop blocks of verbatim text.  See https://guides.github.com/features/mastering-markdown/, and click on the "code" tab in the "Examples" section.

**Comment by wgropp** [comment]
That's the problem - I *did* use the code tab - and you see what I got. Wesley's suggestion I'll try to remember, as it isn't an option on the menu (seems odd, as that would be *exactly* the formatting you'd expect to need *most* when working on source code...)

**Comment by martinruefenacht** [comment]
@wgropp Last year you requested we use Python2, but since then it has gone end of life (beginning of this year) so we decided to switch back to Python37.

1. From the error blurb, you will need to install Python 3.7 (at least).
2. Then you will need to make sure pip is installed, the package manager.
[pip install on mac](https://ehmatthes.github.io/pcc/chapter_12/installing_pip.html#pip-on-os-x)

This will give you the required environment that you need to execute pytest in the directory, either:
- python3.7 -m pytest
- pytest
- make pythoncheck

You can also use Python 3.8 it is backward compatible.

With the latest feat-python-ci you can use "make pythoncheck" which will automatically download the packages you need assuming you have Python and pip installed.

**Comment by wgropp** [comment]
Mac Catalina comes with a Python 3.7 installed, as python3. My suggestion for python2 was only that we should use versions that are common on major platforms used for writing the standard, such as Macs. However, the above doesn't work for me.  pip is installed:
```% which pip
/usr/local/bin/pip
gropp@wdg-macbook ~ %
```
but
```
% python3 -m pytest
/usr/local/bin/python3: No module named pytest
gropp@wdg-macbook ~ %
```
What should Mac Catalina users do?

**Comment by martinruefenacht** [comment]
The "make pythoncheck" should automatically install the dependencies, pytest with plugins. If you want to do it manually without the make rule then attempt:

> pip install --user -r requirements-test.txt

in the python-ci branch.

I agree that if anyone wants to manually run the tests we should just tell them to do "make pythoncheck", which allows us to establish the environment or gracefully fail.

**Comment by wgropp** [comment]
I'm still running into issues, probably because of the state of the python environment on Macs.  However, we need to have a solution for people like me that are running on a Mac.
The `pip install --user -r requirements-test.txt` fails, and at the end says
```
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0y/l_cg3z3d7vs3zkx4h9mrjg_40000gp/T/pip-install-FJ2P1M/pytest-azurepipelines/
You are using pip version 18.0, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
gropp@wdg-macbook mpi-standard % pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.0
    Uninstalling pip-18.0:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pip-18.0.dist-info/INSTALLER'
Consider using the `--user` option or check the permissions.

You are using pip version 18.0, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
gropp@wdg-macbook mpi-standard %
```
Note the amusing second command - I did what it told me to do to upgrade pip, and that failed.
I had to do
```
sudo pip install --upgrade pip
```
That may have been a mistake, because then I got this:
```
% pip install --user -r requirements-test.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pytest
  Using cached pytest-4.6.9-py2.py3-none-any.whl (231 kB)
Collecting pytest-cov
  Using cached pytest_cov-2.8.1-py2.py3-none-any.whl (18 kB)
Collecting pytest-azurepipelines
  Using cached pytest-azurepipelines-0.8.0.tar.gz (6.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0y/l_cg3z3d7vs3zkx4h9mrjg_40000gp/T/pip-install-Z5OnH6/pytest-azurepipelines/setup.py'"'"'; __file__='"'"'/private/var/folders/0y/l_cg3z3d7vs3zkx4h9mrjg_40000gp/T/pip-install-Z5OnH6/pytest-azurepipelines/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/0y/l_cg3z3d7vs3zkx4h9mrjg_40000gp/T/pip-install-Z5OnH6/pytest-azurepipelines/pip-egg-info
         cwd: /private/var/folders/0y/l_cg3z3d7vs3zkx4h9mrjg_40000gp/T/pip-install-Z5OnH6/pytest-azurepipelines/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0y/l_cg3z3d7vs3zkx4h9mrjg_40000gp/T/pip-install-Z5OnH6/pytest-azurepipelines/setup.py", line 54, in <module>
        'azurepipelines = pytest_azurepipelines',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Python/2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/Library/Python/2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 258, in finalize_options
        ep.load()(self, ep.name, value)
      File "/Library/Python/2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1994, in load
        raise ImportError("%r has no %r attribute" % (entry,attr))
    ImportError: <module 'setuptools.dist' from '/Library/Python/2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.pyc'> has no 'check_specifier' attribute
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
gropp@wdg-macbook mpi-standard %
```
It looks like pip is wired to python2.7 . There is a `pip3`:
```
% which pip3
/usr/bin/pip3
gropp@wdg-macbook mpi-standard % pip3 --version
pip 19.0.3 from /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
gropp@wdg-macbook mpi-standard %
```
Should I be using this instead?

**Comment by martinruefenacht** [comment]
Yes, I think that is the problem. Sadly until python2 is properly purged from all OSs I think we need to make it explicit to use pip3 and python3. Apple does a horrendous job at giving us control over our environments... I have a mac myself and it has been a struggle until one day I say down and kill anything related to Apple.

**Comment by martinruefenacht** [comment]
@wgropp Could I own this ticket? I can do the changes and use it as a test case for the python-ci.

**Comment by wgropp** [comment]
Yes, please own this ticket. Thanks!

**Comment by wgropp** [comment]
I think that for this small group, we can have careful instructions - these will have to start by helping people identify how to run the correct versions and not assume python and pip give the desired versions.

**Comment by martinruefenacht** [comment]
The PR does not include the Python CI testing. I decided to separate it and make a dedicated PR due to potential changes wanted.
