### ISSUE TITLE
Update: Multiple occurances - Non(-?)blocking

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#231]
## Problem

Is it non-blocking or nonblocking? Is non-blocking preferred?

### Suggested Fix

Use non-blocking

**Comment by jaegerj** [comment]
As the term defined in MPI since 1.0 is "nonblocking", I would rather use "nonblocking" everywhere.

Also, I am willing to handle this ticket.

**Comment by wesbland** [comment]
Everyone voted this as an editor change so @jaegerj can just get this reviewed by @wgropp when he's done to make sure they agree (or maybe before since they don't seem to agree).

**Comment by dholmes-epcc-ed-ac-uk** [comment]
As @jaegerj says, the Semantic Terms WG decided to continue with the terms "nonblocking" and "non-local" because they seemed to be the most commonly used form and are the way those terms were spelt in their definitions in previous versions of MPI.

Given what we now know about the meaning of these terms, I tend to favour changing to "non-blocking" throughout the document. There is a subtle impression that "non-thing" implies "not thing" or "the opposite/converse of thing" for example "non-essential" implies "not essential" (this is what we now intend as the meaning for both terms). However, the "nonthing" form often subtly implies that the meaning is different, although possibly somewhat related, to "not thing". For example, "nonsense" does not mean "not sense", although it does convey "makes no sense".

Personally, I think this should be a change proposed by the Semantic Terms WG - possibly as part of the existing issue #96 or maybe as a separate errata/full proposal issue.

**Comment by RolfRabenseifner** [comment]
Oh please keep "nonblocking" and "non-local" spelling as it is.
All literature and teaching on MPI should have used exactly
this spelling to be consistent with the MPI Standard for more
than 25 years.
It should not be our fault to make all this immense work
inconsistent with the MPI Standard.
Rolf


-- 
Dr. Rolf Rabenseifner . . . . . . . . . .. email rabenseifner@hlrs.de .
High Performance Computing Center (HLRS) . phone ++49(0)711/685-65530 .
University of Stuttgart . . . . . . . . .. fax ++49(0)711 / 685-65832 .
Head of Dpmt Parallel Computing . . . www.hlrs.de/people/rabenseifner .
Nobelstr. 19, D-70550 Stuttgart, Germany . . . . (Office: Room 1.307) .

**Comment by jaegerj** [comment]
Ok, we definitely need to discuss more about this, because I am thinking that @dholmes-epcc-ed-ac-uk  explanation tends to favor "nonblocking" for two reasons:

1) As said, "non-blocking" tends to imply "not blocking". But we kind of established that the MPI definition of nonblocking is not really correlated to the english meaning of "does not block". Using the hyphen may be even more misleading.

2) Also, so far, we were not able to define the MPI "blocking" term on its ow, and we still rely on saying "is not nonblocking". If using "non-bloclink", it may also imply indirectly that "non-blocking" is "not blocking" in the MPI sense, but the "blocking" definition we are stuck with in the WG is "not nonblocking". So, it kind of implies a circular definition between this two terms, which is not helping. "nonblocking" can be a stand-alone term on itw own, which then breaks the circular definition.

I agree that we should find a common ground in the Semantic Terms WG.
I personally think that "just" harmonizing the orthograph of "nonblocking" (or "non-blocking") through the document is just an errata.

**Comment by jaegerj** [comment]
Well, it seems the only reference to "non-blocking" in the current 4.0 document are only in reference titles.
I am not sure this ticket is relevant anymore.
