### ISSUE TITLE
Update: Multiple occurances - Index Progress

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#234]
## Problem

Consider adding progress to index.  Insure mpi, mpif.h, mpi_f08 in the correct font in the index.

### Suggested Fix

Add progress to index; update font for Fortran include/modules.

**Comment by wesbland** [comment]
Editor change:

* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0

**Comment by RolfRabenseifner** [comment]
Bill, this is the content of my progress slide. I hope the references may help you.
____
# General progress rule of MPI

MPI is mainly defined in a way that progress on communication (and …)
is required only during MPI procedure calls.
- But then, progress is required
  - for all outstanding (incomplete/ nonblocking ) communications
  - together with operation of the current communication (…) procedure call.

- See , e.g., in MPI 3.1
  - Sect. 3.5, page 41, and 3.7.4, page 56; Paragraphs “Progress”
  - Sect. 3.8.1 and 3.8.2 about MPI_(I)( M)PROBE
  - Sect. 3.8.4 Cancel, esp. page 73 lines 17 25 & MPI_Finalize Example 8.9, page 358 359
  - Sect. 5.12: Nonblocking collectives: Same rules as for nonblocking pt to pt
  - Sect. 11.7.3: Progress with one sided communication, especially the **rationale at the end** !!
  - Sect. 12.4: MPI and Threads
  - Sect. 13.6.3: Progress with MPI I/O

- Non of these rules require progress outside of called MPI routines,
  - But MPI_Test and each MPI routine that blocks must do progress on any ongoing (i.e. nonblocking ) communication

- Additional progress
  - By several calls to MPI_Test (), which enables progress
  - Use non standard extensions to switch on asynchronous progress
     - E.g., with MPICH: export MPICH_ASYNC_PROGRESS=1 (Implies a helper thread and MPI_THREAD_MULTIPLE)

____

**Comment by dholmes-epcc-ed-ac-uk** [comment]
A minor point, perhaps not relevant here per se, but does a progress thread inside MPI imply MPI_THREAD_MULTIPLE is necessary in user code? The user cannot use MPI_THREAD_SINGLE (which means "there is exactly one thread per MPI process") because the progress thread is a distinct (non-user) thread. However, even MPI_THREAD_FUNNELLED is okay from the user code perspective - all user calls into MPI can be marshalled onto a single user thread in order to comply with the restriction. The work of the internal progress thread is not (necessarily) done via user-level MPI calls.

This is a very useful list of references, thanks.

**Comment by wgropp** [comment]
No, it doesn't imply MPI_THREAD_ MULTIPLE is necessary in user code.  Note that an MPI implementation may deliver any thread level that it wants, so an easy implementation choice when there is a helper thread is to work at the THREAD_MULTIPLE level. But an implementation could choose to do something else; one of the the reasons that MPI is so careful not to dictate implementation choices.

**Comment by wgropp** [comment]
Font for Fortran mpif.h and modules mpi and mpi_f08 fixed.  Much of progress is now indexed; I'll make one more review.
