### ISSUE TITLE
Clarification: Section 5.1 - p. 144 - Collective Synchronization

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#257]
## Problem

On the second page, there is the statement "This statement excludes, of course, the barrier operation.". However, in the context where this is placed, there are other collectives which are synchronizing by their semantics (not just their implementation), e.g., Allreduce and Alltoall. As such, this text is misleading.  A fix is to mention routines that are semantically synchronizing, and give a few examples without providing a complete list.

### Suggested Fix

Simplest is to add "and other routines whose semantics imply synchronization."

**Comment by jaegerj** [comment]
I can deal with this issue.

**Comment by wesbland** [comment]
The group seems to think this should be an errata:

* Editor - 0
* Chapter committee - 3
* Errata - 3
* Full Proposal - 1

**Comment by RolfRabenseifner** [comment]
The sentence MPI-3.1 page 142 lines 28-29 is correct and should not be changed.
More details will be mentioned in new Annex A.2, see https://github.com/mpi-forum/mpi-issues/issues/96. 
Reason:
All data communicating collective MPI procedures have a count argument that is allowed to be zero. The definition of the routines are typically written like MPI-3.1, page 171 lines 5-11 for MPI_ALLTOALLV:

"The outcome is as if each process sent a message to every other process with
  MPI_Send(...)
 and received ...
  MPI_Resc(...)"

There is an additional Advice to implementors on "use a tree communication pattern".

But the major question is, is it allowed to imit empty messages?

First, already 20 years ago, MPI implementations removed the empty messages to efficiently implement sparse communication patterns.
Are these MPI libraries correct?

A look at Merriam-Webster:

>  Definition of outcome
>  : something that follows as a result or consequence 
>  //a surprising outcome
>  //patient outcomes of bypass surgery
>  //We are still awaiting the final outcome of the trial.

Especially the outcome of the trial, it is not the way to get the result, i.e., all the communications between all actors, it is the sentence at the end. With this reading of "outcome", the synchronizations needed to achieve the outcome are not part of the outcome. And therefore, it is allowed to remove not needed synchronizations. 

And therefore, I would not change the intro of the Collective Communications chapter.

But one may add "**Also, empty messages need not to be communicated.**" at the end of this first performance-oriented advice to implementors within the collective chapter.

**Comment by jaegerj** [comment]
Thank you for your comment @RolfRabenseifner .
So, I have one question about this ticket:
Do people prefer to leave this sentence as is, or to add something like "and other routines whose semantics imply synchronization, as long as all count arguments values are greater than 0"?

**Comment by wgropp** [comment]
We should be careful here. The question is whether the definition in terms of MPI_Send and MPI_Recv is specifying unintended semantics - that even for count zero, messages need to be sent. An advice to implementors doesn't change the semantics of an MPI procedure. I'd prefer something that make explicit that the description of operations as if they were implemented with MPI_Send and MPI_Recv is not exact; and the count==0 case is an example. Another is that the collectives are more strict about message size matching, and error returns aren't the same.

**Comment by jaegerj** [comment]
To be fair, I think the text already does that. It says that "the outcome" of the collective is "as if" MPI_Send and MPI_Recv with the same arguments have been issued. As I understand it know, after reading this again more carefully, this sentence is an indication about what the output should look like, and not what is the expected behavior of the collective in terms of actual message sending and receiving.
Just for the correction of the original issue, either leaving it as is or my suggested fix can be enough.

If we want, we can create a new issue to add advice to implementors saying that, in such places, these sentences only relate to the output of the collective and not its behavior. Especially, in the case of count==0, it is not required that empty messages should be send or received.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
The possibility of specifying unintended semantics by using point-to-point to illustrate data-movement is already recognised and excluded. Last paragraph in section 5.1 in MPI-3.1:

> 14 Many of the descriptions of the collective routines provide illustrations in terms of
15 blocking MPI point-to-point routines. These are intended solely to indicate what data is
16 sent or received by what process. Many of these examples are not correct MPI programs;
17 for purposes of simplicity, they often assume infinite buffering.

**Comment by wgropp** [comment]
Well spotted. That leaves the original issue.

**Comment by jaegerj** [comment]
I'll try to provide a replacement text, taking into account the possibility that count==0 may "break" the synchronizing behavior of the original semantics. Then, the Forum can decide if we should leave the text as is or adopt a replacement text.

**Comment by jaegerj** [comment]
Actually, reading again this section, the sentence "This statement excludes, of course, the barrier operation." refers to "Thus, a collective communication operation may, or may not,
have the effect of synchronizing all calling processes.".
It is true for a barrier with an intracommunicator, but not with an intercommunicator.
For an intercommunicator, the barrier definition is specifically saying that "A process may return from
the call before all processes in its own group have entered the call."

In the general collective introduction, it is also clearly stated that "The completion of a collective operation indicates that the caller is free to modify locations in the communication buffer. It does not indicate that other processes in the group have completed or even started the operation (unless otherwise implied by the description of the operation). "


As a result, should we just remove the sentence "This statement excludes, of course, the barrier operation.", as it isn't even true for barrier?

**Comment by omor1** [comment]
In general, based on this discussion, it seems to be difficult to paint the behavior of these operations correctly with a broad stroke, as the exceptions seem to themselves have exceptions. Perhaps it may be better (and more accurate) to remove _both_ sentences and replace them with language to the effect of:
> The synchronization behavior of collective communication operations is described in detail in the documentation of each operation.

**Comment by RolfRabenseifner** [comment]
Personal remark: Although it looks like a short errata, it seems to be more dangerous and may need therefore to be a full proposal.
We discuss the highlighted sentences of the following Paragraph (MPI-3.1 Section 5.1 page 142 lines 21-29):

> Collective operations can (but are not required to) complete as soon as the caller's
participation in the collective communication is finished. A blocking operation is complete
as soon as the call returns. A nonblocking (immediate) call requires a separate completion
call (cf. Section 3.7). The completion of a collective operation indicates that the caller is free
to modify locations in the communication buffer. It does not indicate that other processes
in the group have completed or even started the operation (unless otherwise implied by the
description of the operation). **Thus, a collective communication operation may, or may not,
have the effect of synchronizing all calling processes. This statement excludes, of course,
the barrier operation.**

One must carefully distinguish between procedure call and operation (which, e.g., can be the combination of MPI_I.... + MPI_Wait).

The current "Semantic terms" section (MPI-3.1, Section 2.4, page 11, lines

**Comment by jaegerj** [comment]
On the last virtual meeting, we decided to go with the removal of the sentence: "This statement excludes, of course, the barrier operation."
Regarding the other sentence "Thus, a collective communication operation may, or may not,
have the effect of synchronizing all calling processes.", a similar issue is discussed in the Terms WG. It was decided to discuss the future of this sentence once the discussion in Terms WG provides a valid replacement.

Regarding original sentence removal in the collective chapter intro, here is an annotated MPI 4.0 pdf with red changebars.
[mpi40-report_issue_257.pdf](https://github.com/mpi-forum/mpi-issues/files/4657671/mpi40-report_issue_257.pdf)

**Comment by wesbland** [comment]
This passed an errata vote on 2020-07-01.

https://www.mpi-forum.org/meetings/2020/06/votes
