### ISSUE TITLE
Deprecate point-to-point send cancel

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#26]
# Problem

In MPI-3.1, it is valid to call MPI_Cancel on send requests. This is hard to implement efficiently. For example, some MPI implementations are required to send additional information (such as a sequence number) with each operation to allow for operations to be potentially cancelled. The original reason to add cancel capability for send operations was for symmetry with receive operations. But that reason is no longer true since cancel operations are not support for nonblocking collective communication, RMA or file I/O operations.
# Proposal

Deprecate the usage of MPI_Cancel for send requests. Implementations are free to implement it if they like, but the user cannot rely on it functioning correctly. Specifically, calling MPI_Cancel on send requests is valid (not erroneous) but users should be aware that many current implementations are incorrect meaning that the operation might result in undefined incorrect behaviour. For example, no request is ever cancelled, the wrong is request is cancelled, the correct request is cancelled but not in a timely manner (such as during MPI_FINALIZE).

Note: this is the de facto state of MPI implementations today. Some (though very few) implementations implement it correctly. Users do not use it since most implementations do not implement it correctly.
# Text Changes

[issue-26-diff.txt](https://github.com/mpi-forum/mpi-issues/files/524521/issue-26-diff.txt)

+Terms chapter - new entry for deprecation of send cancel in deprecated and removed table
+Point-to-point chapter - mentioned deprecation 4 times for different usages
+Environmental management chapter - mentioned deprecation in example of MPI_CANCEL usage
+Deprecated chapter - new section for MPI-3.2, new entry for deprecation of send cancel
+Change log chapter - new section for MPI-3.2, new entry for deprecation of send cancel
+General index - added references to new mentions of cancel (and some existing ones)
+Function index - added references to new mentions of MPI_CANCEL
# Impact on Implementations

Joy and celebration.
# Impact on Users

Huh? Send cancellation was allowed earlier?
# Draft standard

[issue-26-mpi32-report.pdf](https://github.com/mpi-forum/mpi-issues/files/524522/issue-26-mpi32-report.pdf)

**Comment by jdinan** [comment]
A changelog entry (or course, the proposal I put forward doesn't include one either) will be important, since this is a semantic change by deletion.  I'm not sure when this is supposed to be done, but we should make sure we don't forget.

**Comment by RolfRabenseifner** [comment]
Jim,

   your proposal must include the changelog entry.
   otherwise, you, all reviewers, and finally the MPI Forum
   should reject your proposal because it is "of course"
   incomplete and would make the MPI Standard in this sense
   inconsistent.

All reviers and Forum members,
   please,
   never accept proposals that are incomplete 
   or inconsistent with the MPI Standard.

Best regards
Rolf

----- Original Message -----
> From: "James Dinan" <notifications@github.com>
> To: "mpi-forum/mpi-issues" <mpi-issues@noreply.github.com>
> Sent: Thursday, February 25, 2016 3:27:07 AM
> Subject: Re: [mpi-issues] Deprecate point-to-point send cancel (#26)

> A changelog entry (or course, the proposal I put forward doesn't include one
> either) will be important, since this is a semantic change by deletion.  I'm
> not sure when this is supposed to be done, but we should make sure we don't
> forget.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mpi-forum/mpi-issues/issues/26#issuecomment-188570027

-- 
Dr. Rolf Rabenseifner . . . . . . . . . .. email rabenseifner@hlrs.de
High Performance Computing Center (HLRS) . phone ++49(0)711/685-65530
University of Stuttgart . . . . . . . . .. fax ++49(0)711 / 685-65832
Head of Dpmt Parallel Computing . . . www.hlrs.de/people/rabenseifner
Nobelstr. 19, D-70550 Stuttgart, Germany . . . . (Office: Room 1.307)

**Comment by jdinan** [comment]
@dholmes-epcc-ed-ac-uk, sorry, I was reading the text above, which appears to be out dated.  Could you reference PR mpi-forum/mpi-standard#15 from this issue, since this is what's listed in the agenda?

@RolfRabenseifner, This proposal does include a changelog entry.  I'll add one to the other proposal I mentioned.

**Comment by rsth** [comment]
Is there supposed to be a pdf of the change for the reading? Not everyone can see the git diff unless they are part of the working group. And one can miss things by looking just at the diff, i.e., the context of what is above and below the changes.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Updated text based on feedback at March meeting.

The pdf with change markers is as follows:
[mpi-report.pdf](https://github.com/mpi-forum/mpi-issues/files/277631/mpi-report.pdf)

**Comment by RolfRabenseifner** [comment]
Perfect, with only one tiny exception:
In the Change-log, the doubled referencing of current and previous MPI is done only for errata, because they Change the previos MPI Version, too. In your case, the old reference
    ", and MPI-3.1 Section 3.8.4 on page 71"
should be removed.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Thanks @RolfRabenseifner - I have fixed the pull request, diff, and draft standard.
