### ISSUE TITLE
Define new MPI Error handler for subcommunicator abort

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#3]
This ticket came out of the discussion with ticket #1. While it is a separate ticket, the two probably should be considered together and share a PDF.

This ticket introduces a new MPI error handler which causes only the communicator on which it is called to be aborted. This separates the undefined and somewhat dualistic behavior of MPI-3.1 `MPI_ERRORS_ARE_FATAL` into ticket #324, which says that `MPI_ERRORS_ARE_FATAL` will cause all connected processes will abort, and this ticket, which introduces a new error handler, `MPI_ERRORS_ABORT`, which causes only the communicator to abort.
# PDF

[issues-1-3.pdf](https://github.com/mpi-forum/mpi-issues/files/1282445/issues-1-3.pdf)

**Comment by jsquyres** [comment]
[tickets-1-3.pdf](https://github.com/mpi-forum/mpi-issues/files/2573/tickets-1-3.pdf)

**Comment by wesbland** [comment]
Here is the latest version of the PDF: [issues-1-3.pdf](https://github.com/mpi-forum/mpi-issues/files/127191/issues-1-3.pdf)

The pull request can be found at mpi-forum/mpi-standard#1 and has the full colorized diff.

**Comment by rainwoodman** [comment]
Not quite the right place to ask, but is the new or current error handling in MPI able to maintain a state on a communicator such that all subsequential operations on the communicator returns an error? 
It is an error state that is more benign than MPI_Abort -- MPI_Abort kills everybody. But in a language binding we want to be able to collectively raise an exception when a single rank encounters an exception (which can be totally unrelated to MPI), rather than killing all ranks directly..

**Comment by abouteiller** [comment]
Indeed not the right place to ask. What you are looking for is another proposal named ULFM. You can gain more information about how to use it on http://fault-tolerance.org

**Comment by rainwoodman** [comment]
Thanks! This indeed is exactly what we wanted. However, before this is merged into upstream MPI and implemented by vendors we are stuck with the all killing MPI_Abort. Hope it happens soon.

**Comment by wesbland** [comment]
[Marked up PDF for reading](https://github.com/mpi-forum/mpi-issues/files/1300379/issues-1-3-markedup.pdf)

**Comment by schulzm** [comment]
Passed second vote at June 2018 meeting in Austin
