### ISSUE TITLE
Accessing a memory allocated by MPI_Win_shared_allocate MANY times slower compared to accessing an array through a raw pointer

### ISSUE THREAD

**Issue by akjt** [mpi-forum/mpi-issues#330]
`
This code compares the performance by accessing and filling up an array which is either allocated by MPI_Win_shared_allocate and the standard C way through malloc. I have tested on several machines and it is shown to be many times slower. 

#include <mpi.h>
#include<stdlib.h>
int main( int argc, char *argv[])
{
MPI_Init(&argc, &argv);
MPI_Win win;
MPI_Comm MPI_COMM_SHM;
int rank;
long int mb = 0;
double* bufptr;

MPI_Comm_rank( MPI_COMM_WORLD, &rank );
int MB = 10000;
if(rank==0)mb = MB*1e6/sizeof(double);

MPI_Comm_split_type( MPI_COMM_WORLD, MPI_COMM_TYPE_SHARED, 0, MPI_INFO_NULL, &MPI_COMM_SHM);

MPI_Aint size_bytes,size_of_T, lb;

MPI_Info infoAlloc;
MPI_Info_create( &infoAlloc );
MPI_Info_set( infoAlloc, "alloc_shared_noncontig", "true" );
MPI_Type_get_extent(MPI_DOUBLE_PRECISION, &lb, &size_of_T);

size_bytes = mb*size_of_T;
int disp_unit = size_of_T;
printf("%ld   %ld   %d\n", size_bytes, mb, size_of_T);
MPI_Win_allocate_shared( size_bytes, disp_unit, infoAlloc
                        , MPI_COMM_SHM, &bufptr, &win);

double *rbuf;
MPI_Aint  rsize;
int disp;
if(rank != 0)
{
   MPI_Win_shared_query(win, 0, &rsize, &disp, &rbuf);
   printf("rbuf %d  %ld\n", rank, rsize);// WHY IS THIS not the size itself but in bytes????
}

if(rank==0)
{
   double t1= MPI_Wtime();
   for(long int i = 0; i<mb; i++)
   {
      bufptr[i] = (double) (rank+1)*i;
   }
   double t2 = MPI_Wtime();
   printf("time taken using shared buffer %e\n", t2-t1);
}

MPI_Win_free(&win);

if(rank==0)
{
   double* test_;
   test_ = (double*) malloc(sizeof(double)*mb);
   double t1= MPI_Wtime();
   for(long int i = 0; i<mb; i++)
   {
      test_[i] = (double) (rank+1)*i;
   }
      double t2= MPI_Wtime();
   printf("Time taken using raw pointer  %e\n", t2-t1);

   // NOTE: do not remove this dummy lines below... Compiler optimisation will remove the loop above if it does not see test_ being used elsewhere!!
   double sum_;
   for(long int i = 0; i<mb; i++)
   {
      sum_ += test_[i];
   }
   printf("__ %e\n\n", sum_);
}

MPI_Finalize();
}

`

**Comment by pavanbalaji** [comment]
Yes, it's a known issue (https://www.mcs.anl.gov/~balaji/pubs/2015/ppmm/ppmm15.stencil.pdf).  This is because of at least two reasons:

1. malloc buffers are treated differently by the compiler.  You can emulate the same behavior for `MPI_Win_allocate_shared` buffers by using restrict pointers.

2. malloc buffers are given huge pages by the OS (at least on linux), while the `MPI_Win_allocate_shared` buffer gets regular pages.  So it has more TLB misses.

**Comment by akjt** [comment]
Thanks for the paper!! 
1) I tried to declare the pointer as `double * __restrict bufptr`. I did not find it to help.

**Comment by pavanbalaji** [comment]
You might need to look at the assembly code generated to figure out the difference.  In our experiments, declaring the buffer as a restrict pointer regained most of the performance.

**Comment by akjt** [comment]
Thank you. Just FYI I tried with the Intel MPI and intel compiler using the restrict keyword. Apparently I oversaw a warning saying that it is discarding the "restrict" because I am passing it to MPI_Win_shared_allocate which expects a "void *". It did not improve the performance at all when I run at. 

When switching over to mpich with a GCC compiler it worked and I am attaining similar performance now.

**Comment by pavanbalaji** [comment]
You can cast it to restrict after the buffer is allocated too.

**Comment by hjelmn** [comment]
There are lots of reasons why the memory may be slower. The primary reason is likely nothing to do with how the compiler treats malloc. It is **never** __restrict by default. That would violate the C standard.

We had a performance bug in Open MPI because we pinned all the window memory to the first controller. This was due to registering the memory with the lowest rank processor (to limit the number of memory registrations) before it was touched by any other processs. This meant that any process not in the first memory domain incurred extra latency when accessing the memory. That was fixed by adding a first touch before the registration step. As for huge pages.... They are not usually allocated by default unless you are on a Cray and specifically loaded a hugepage module-- this is non-standard behavior. You need to specifically request them on Linux. There are various reasons for this. The MPI implementation is perfectly free to allocate huge pages to back a window allocated by ```MPI_Win_allocate```.

__restrict will, in general, help performance by indicating to the processor that you are not aliasing memory. C/C++ will assume arrays could be aliased by default. The __restrict keyword disables that assumption.

Also, this question would have been best directed at one or more of the implementations. This issue list is for the MPI standard not any particular implementation.

**Comment by jeffhammond** [comment]
> As for huge pages.... They are not usually allocated by default unless you are on a Cray and specifically loaded a hugepage module-- this is non-standard behavior. You need to specifically request them on Linux. 

https://linux.die.net/man/7/libhugetlbfs explains that one can override the `malloc` defaults with huge pages and other useful things without needing Cray Linux.

**Comment by christgau** [comment]
> > As for huge pages.... They are not usually allocated by default unless you are on a Cray and specifically loaded a hugepage module-- this is non-standard behavior. You need to specifically request them on Linux.
> 
> https://linux.die.net/man/7/libhugetlbfs explains that one can override the `malloc` defaults with huge pages and other useful things without needing Cray Linux.

And there are "[Transparent Huge Pages](https://www.kernel.org/doc/html/latest/admin-guide/mm/transhuge.html)" (THP). If activated, the malloc implementation may return you memory that is backed by huge pages even if the implementation (or your own call to mmap) did not explicitly requested them.
