### ISSUE TITLE
MPI 4.0 RC Reference chapter review issues

### ISSUE THREAD

**Issue by rlgraham32** [mpi-forum/mpi-issues#339]
Issues that came up in the review:

* Reference 1 - Page 337:
```
included in MPI_COMM_WORLD and hwcomm[1]. For the first splitting operation, the
                                     ^^^
```
Should be reference 67
* Reference 46: section 19.1.1 is listed twice and there are actually 2 references to it in this section.  Section 19.1.7 is listed once but has 2 references to it in this section. Just need to be consistent.

**Comment by GuillaumeMercier** [comment]
I'm not sure I understand your first issue: `hcomm[1]` is not a reference, it's the second element in the array `hcomm`, as the example's legend explains. Or did I misunderstood?

**Comment by wesbland** [comment]
I think the first issue here is resolved, but the second needs to be figured out. There isn't a chapter committee for the bibliography, so I assume this should go to @wgropp.

**Comment by wgropp** [comment]
The links in the bibliography are generated automatically by the backref option in hyperref.    Changing this is hard; it requires changing the hyperref package, which is very complex. Here's what appears to be happening.  I checked the mpi-report.brf file, and the hyperref package removes duplicate entries.  That explains why there is only one entry for 19.1.7 for reference 46.  For the 19.1.1 entries, one is "subsection.19.1.1" but the other is "Item.83" - probably because of a list environment used before that second reference. One option is to switch to backref=page - this then displays the page number, rather than the section number, and duplicates are removed on the basis of the page number. I can make this change to avoid the confusing formatting of the default (which IMHO is a bug in hyperref)

**Comment by bkmgit** [comment]
Not sure if there is an issue for this:
https://github.com/latex3/hyperref
backref seems to use a different development model
https://www.ctan.org/pkg/backref

**Comment by wgropp** [comment]
I think the real problem is a design problem in hyperref.  For naming the location, section titles aren't precise enough, and since the citation doesn't have a location label, the package appears to be using the "closest" label. This sounds like a good idea, but really isn't. 

I've pushed a change to use backref=page

**Comment by wesbland** [comment]
I assume this issue can be closed now (reopen if someone disagrees)?
