### ISSUE TITLE
Frontmatter Chapter RC Review Issues

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#348]
# Problem

RC Review - all references refer to the printed page numbers of
https://github.com/mpi-forum/mpi-forum.github.io/raw/master/docs/mpi-4.0/mpi40-rc-nov-20.pdf 

# Proposal

To change the inconsistencies, ...

# Changes to the Text

1. All capital letters or mixed:

- [x] "Steering Committe" versus "Steering committee"
- [x] "Meeting Chair" versus "Meeting chair"
- [x] "MPI_... Secretary" versus "MPI secretary"
- [x] "Front matter"

All this is inconsistent already in MPI-3.0
It start with with all caps
 - Jack Dongarra, David Walker, Conveners and Meeting Chairs

and seems to be the first time broken 
 - xxix:14 "MPI-2.2 chair"

wheras 
- xxix:31 "MPI-2.2 Secretary" is still all caps

Locations that may be switched to caps may be xxix:14, xxxi:27+29+30+45, xxxiii:45+47+48, xxxiv:1+4, xxxvi:3+8+11

2. Names for 4.0 without nicknames:

- [x] xxxvi:14 Purushotham V. Bangalore
- [x] xxxvi:38 James Dinan
- [x] xxxvi:46 Purushotham V. Bangalore

3. Currently, https://www.mpi-forum.org/mpi-40/ does not tell the chair(s) of Large Count.

- [x] My impression was that it was lead by a team.
- [x] xxxvi:40 Is "Large Counts Jeff Hammond" correct?

4. To be consistent with all previous lists, xxxiv:23 and xxxvii:4 should be appended by:
"and who are not mentioned above". 
Duplicated entries in lists xxxiv:25-xxxv:7 and xxxvii:6-xxxvii:2 should be removed.

Response - the approach to the lists changed during the standard, and these are correct as written. There is no need to change these. 

5. Alphabetic: 

- [x] xxxvii:27+33: Ignacio Laguna Peralta is twice. Lastname is "Laguna Peralta" - therefore should be only in 27 with full name
- [x] xxxvii:45: Isaias Alberto Compres Urena. Lastname is "Compres Urena" - should be moved in line 13 after Clauss
- [x] xxxvii:46: Manjunath Gorentla Venkata. Lastname is "Gorentla Venkata" - should be moved to line 18 after Goglin
- [x] xxxvii:? Was Collective... group co-chair Andrew Lumsdaine never on a meeting ...? I miss him in this list.

6. xxxviii:17 and 24: 

- [x] Cray and HPE: What are the rules for company mergers? (See below - use both in this list)

7. xxxviii:20+29+29: 

- [ ] Are all three independent institutions?

8. xxxix:1 

- [x] "Of" --> "of" (plus a search found two more to fix)

# Impact on Implementations

None.

# Impact on Users

None.

# References

https://github.com/mpi-forum/mpi-forum.github.io/raw/master/docs/mpi-4.0/mpi40-rc-nov-20.pdf

**Comment by schulzm** [comment]
Additional Comments (based on review from pages 1-26):

Obvious changes that still need to be done and reviewed:
- Page 2, Intro comments
- Page 3, First Paragraph

Minor changes:
- Page 2, line 6: “and a profiling interface” -> “multiple tool interfaces”
- Page 3, line 38: lower case for chapter
- We are missing the convener for MPI 4.0
- Page 23, line 6: no comma
- Page 39, line 1: lower case "o" in "Of"
- Page 39, line 12: University of Potsdam (instead of Pottsdam)

Questions to discuss:
- Page 4, Version 1.0: I would suggest to drop the abbreviation MPIF for the forum, since it is not used anywhere else in the standard, not used commonly (aymore?) and may be confusing
- Table of contents: should subsubsubsections without numbers be actually listed here?
- is it “Message-Passing” or “Message Passing”? – even for the name of the standard, that is currently not consistent.

**Comment by AOA-Mohammed** [comment]
Can you please also add my name (Ali Mohammed) and organization (University of Basel, Switzerland) in the Acknowledgements for MPI-4.0 (pages 37-39)?

**Comment by wesbland** [comment]
@wgropp I think we may need to re-scrape the attendance logs for the last couple of years since we updated the acknowledgements for one of the preview versions.

**Comment by wgropp** [comment]
Ali - I've added both and they'll be in my next frontmatter PR

**Comment by wgropp** [comment]
For the first set, all are done where I agreed.  The reason for rejecting the others:

- #3 - the committee needs to tell me.
- #4 - We changed how we managed these lists. I do not want to go back and change them.
- #5 - As for #3, the committee needs to tell me
- #6 - This is a historical list, not the list as of a point in time. Thus, but Cray and HPE belong on this list.  Cray will not be on the next list.

**Comment by wgropp** [comment]
On the second set, all done with these exceptions:

- Martin, are you the official convener for 4.0?
- p23, line 6 - we use Oxford commas

And I removed MPIF, since it only occurred in that one place.

**Comment by regrant** [comment]
@wgropp Please add Whit Schonbein from Sandia National Laboratories to the Acknowledgements. Also, if you could please change Ryan Grant to Ryan E. Grant it would be appreciated. Thanks.

**Comment by gpapaure** [comment]
@wgropp Please replace ATOS/BULL institution by Atos
p 10/l10 : replace "ATOS/BULL" by "Atos"

**Comment by wgropp** [comment]
ATOS/BULL -> ATOS for MPI 4.  Whit Schoenbein and Ryan Grant to Ryan E. Grant done in PR 420

**Comment by wgropp** [comment]
There are a few outstanding questions. I've addressed all of the specific items. Can we either close this or get updates for #3 and #5?

**Comment by tonyskjellum** [comment]
Opinion: When it’s a compound adjective , Message-Passing Interface is actually right vs Message Passing as the noun... also High-Performance Computing vs without hyphen ... but we have a history of “Message Passing Interface” ... let’s keep it that way :-) 

Anthony Skjellum, PhD
205-807-4968


On Dec 8, 2020, at 12:21 PM, Wesley Bland <notifications@github.com> wrote:

﻿
@wgropp I think we may need to re-scrape the attendance logs for the last couple of years since we updated the acknowledgements for one of the preview versions.

**Comment by wesbland** [comment]
> 3. Currently, https://www.mpi-forum.org/mpi-40/ does not tell the chair(s) of Large Count.
My impression was that it was lead by a team.
xxxvi:40 Is "Large Counts Jeff Hammond" correct?

Jeff was officially listed as the WG chair when it was moved to the "on hold" list, so it would be correct to list him.

> 5. Alphabetic:
xxxvii:27+33: Ignacio Laguna Peralta is twice. Lastname is "Laguna Peralta" - therefore should be only in 27 with full name
xxxvii:45: Isaias Alberto Compres Urena. Lastname is "Compres Urena" - should be moved in line 13 after Clauss
xxxvii:46: Manjunath Gorentla Venkata. Lastname is "Gorentla Venkata" - should be moved to line 18 after Goglin

These are probably all correct. I never updated my script to take two names into account this way so when I sent them to Bill, they were probably out of order.

xxxvii:? Was Collective... group co-chair Andrew Lumsdaine never on a meeting ...? I miss him in this list.

He is still officially a co-chair of the collectives WG, but the last official forum meeting he attended was the January 2008 meeting so he is not listed in the MPI 4.0 participant acknowledgements.

**Comment by wesbland** [comment]
> 5. Alphabetic:

There's a couple others:

* Marc Gamell Balmana
* Isaias Alberto Compres Urena
  * There are four names here and I'm not sure which one this person prefers to use when alphabetizing. @schulzm - This person is from TU Munich, do you know the answer and/or have the ability to ask?

**Comment by wgropp** [comment]
I've done what I can - I need feedback on the remainder.

**Comment by wesbland** [comment]
@wgropp Where are you still looking for feedback? I thought I'd answered the questions above, but I could have missed something.

**Comment by wgropp** [comment]
Yep, I am.  You helped, but there are still a few open. 

- [ ] MPI 4.0 meeting convener. Was that Martin?
- [ ] Questions about alphabetizing peoples' names (I can leave these as is - it is really everyone's responsibility to check their own name)
- [ ] Should un-unumbered subsubsections be in the TOC?

**Comment by wgropp** [comment]
PR 453 addressed most of the remaining items. Note automatic linking of PRs to issues does not work.

**Comment by wesbland** [comment]
> PR 453 addressed most of the remaining items. Note automatic linking of PRs to issues does not work.

Unfortunately you seem to be correct that issues don't seem to be getting closed automatically, but the linking of PRs to issues for bookkeeping purposes requires a little more formatting than was in that PR.

Instead of just saying "Issue 348" (which has no meaning in the context of that PR because that repository doesn't have issues), you need to say `mpi-forum/mpi-issues#348`. Then if you want it to automatically close (if that starts working), you would say `Fixes mpi-forum/mpi-issues#348`.

**Comment by wesbland** [comment]
> Yep, I am. You helped, but there are still a few open.
> 
> * [ ]  MPI 4.0 meeting convener. Was that Martin?

I think we should change this title to be MPI 4.0 Treasurer given that we changed our rules to say that earlier in the year. Rich holds this role.

> * [ ]  Questions about alphabetizing peoples' names (I can leave these as is - it is really everyone's responsibility to check their own name)

I agree that we should just leave "as is" unless we can reach out to the specific people. 

> * [ ]  Should un-unumbered subsubsections be in the TOC?

IMHO, we should keep whatever we have currently unless someone feels strongly otherwise. If something needs to be in the TOC, it should just get numbered.

**Comment by wgropp** [comment]
I think this is now complete.
