### ISSUE TITLE
Deprecated Interfaces Chapter RC Review Issues

### ISSUE THREAD

**Issue by RolfRabenseifner** [mpi-forum/mpi-issues#354]
- [x] Sect. 16.1, page 770 line 8-9
  - due to macro change, there is a new linefeed between "flag" and "= 0".
- [x] Sect. 16.3, page 772 line 22  **AND** Sect. 16.4, page 772 line 27
  - should be combinded to one Sect. 1.3 Deprecated since MPI-4.0

**Comment by wgropp** [comment]
The first note, the line break in "flag = 0" is not an error - the meaning is clear, and forcing this to be on the same line will make the paragraph right justification ugly. I will leave this as is.

Since there never was an MPI 3.2, I agree with the other fix. However, this needs to be coordinated with fixes to the change log, which has extensive comments on the differences from MPI 3.1 to MPI 3.2.

**Comment by wesbland** [comment]
These two issues appear to be addressed so I'm going to close this.
