### ISSUE TITLE
Tool chapter (partial) RC review

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#365]
From reviewing pages 755-768 in the Nov 2020 4.0 RC document:

* [x] p755 22-23: "previously registered" --> "previously-registered"
* [x] p755 24: "removed" is the wrong word, because there may have been no event callback previously set.
* [x] p755 29: "At invocation time," --> "At callback invocation time,"
* [x] p756 45: "setting" --> "set"
* [x] p756 47: change ; to ,
* [x] p756 48: change ; to ,
* ~~p757 29: remove comma~~ (Comment by @mahermanns: Comma is needed; see discussion on [PR#383](https://github.com/mpi-forum/mpi-standard/pull/383))
* ~~p758 44: remove comma~~ (Comment by @mahermanns: Comma is needed; see discussion on [PR#383](https://github.com/mpi-forum/mpi-standard/pull/383))
* [x] p759 24: "to buffer events and long" --> "to buffer events; long"
* [x] p764 24: "implementation specific" --> "implementation-specific"
* [x] p764 34-35: the notation "in the range 0 and num_cat-1" is a little awkward.  It should probably be "in the range [0, num_cat)" or "in the range of 0 and num_cat-1" or something else.  This same phrasing is also used on p765 2-3, 18-19, 32-33.
* [x] p766 27: "len" is in the wrong font
* [x] p766 35: add comma after "In the latter case"

**Comment by jsquyres** [comment]
FYI @mahermanns

**Comment by mahermanns** [comment]
@jsquyres I created a branch and fixed most of your comments. I will create a PR and associate it with this issue shortly.
One thing that I don't quite unterstand is:
> p764 34-35: the notation "in the range 0 and num_cat-1" is a little awkward. It should probably be "in the range [0, num_cat)" or "in the range of 0 and num_cat-1" or something else. This same phrasing is also used on p765 2-3, 18-19, 32-33.

It reads to me like "the notation *foo* should either be *bar* or *foo* or something else." Am I missing a subtle difference between the initial notation and you second suggestion? I agree it should be consistent. The mathematical notation was discussed once, but in the end we decided against that because not everyone might expect a mathematical notation here, and the difference between `]` and `)` can be subtle but important.

**Comment by wgropp** [comment]
We did have this discussion and the instructions now recommend (sorry, block quote isn't an option apparently)

Ranges of integers should be written out rather than using the mathe- matical notation for an interval. For example, use
values may be between $0$ and $\mpiarg{count}-1$
rather than
    values may be in $[0,count)$

That does suggest a slight change of wording, as I agree that  "in the range 0 and num_cat-1" isn't clear.

**Comment by mahermanns** [comment]
@wgropp @jsquyres I am uncertain on whether I should change the existing text now, or whether we come up with a better wording for 4.1?

**Comment by wgropp** [comment]
I think a change to "in a range from 0 to num_cat-1" is fine and fits in with the format that was the consensus of the Forum (at least, those that participated in the discussions).

**Comment by mahermanns** [comment]
Ok. So just to clarify: I change the **"the range"** to an **"a range"**, because beside this, the text already reads that. I have the feeling I am missing something very subtle here.

**Comment by wgropp** [comment]
The bigger (but still small) change is "from 0 to num_cat-1" from what Jeff was commenting on "0 and num_cat-1"

**Comment by mahermanns** [comment]
Thanks! ... Now I got the difference. Will add this as well.

**Comment by mahermanns** [comment]
@wgropp I updated all references to index ranges I could find throughout the chaper (not only the category occuraces mentioned by Jeff) to *"in the range from 0 to num_X-1"* (i.e., the bigger change), but didn't change the "the" into an "a" in the end, as I thought the "the" would be a better reference to the explicitly given range. What do you think?

**Comment by mahermanns** [comment]
PR for this issue is merged. Closing the ticket.
