### ISSUE TITLE
Deprecated chapter RC review

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#366]
From reviewing pages 769-774 in the Nov 2020 4.0 RC document:

* [x] p772 11: It's a little confusing to mention the removed interfaces in the Deprecated chapter.  Why is that mentioned here?  (removal of the C++ bindings is already described in chapter 17)
* [x] p772: 17: "New Name" column heading should be centered, not right justified
* [x] p772: 22: There was no MPI-3.2 -- I think that the "canceling a send" description should be in the "Deprecated since MPI-4.0" section.
* [x] p773 40: "The following return class ..." --> "The following error class ..."
  From @RolfRabenseifner: Decisision of MPI_T people was that they wanted to change into "return code". Done. 
* [x] p773 40: "by a new name." --> "by a new name in MPI-4.0."

From @naughtont3 (PDF page numbers, i.e., on page 770 as written on the page):

- [x] Page 810, Line 8, should "returning" be "return"
- [x] Page 810, Lines 43-44, "...is the same as [of] the new function, except [of] the function name".
             Should this be: "...is the same as the new function, except for the function name."

**Comment by RolfRabenseifner** [comment]
p772 11: It's a little confusing to mention the removed interfaces in the Deprecated chapter. Why is that mentioned here? (removal of the C++ bindings is already described in chapter 17)
- This chapter is about MPI-2.2. In 2.2, C++ was deprecated.
  More precise wording: "The entire set of C++ language bindings was deprecated as of MPI-2.2 and removed in MPI-3.0. 
  See Chapter 17, Removed Interfaces for more information."

 p772: 17: "New Name" column heading should be centered, not right justified
- and 773:41: as on page page 23 and all double column tables in A.1: left bound columns and headers.

 p772: 22: There was no MPI-3.2 -- I think that the "canceling a send" description should be in the "Deprecated since MPI-4.0" section.
- yes

 p773 40: "The following return class ..." --> "The following error class ..."
 p773 40: "by a new name." --> "by a new name in MPI-4.0."
- yes

From @naughtont3 (PDF page numbers): **You should report this for the language binding chapter 19.**

 Page 810, Line 8, should "returning" be "return"
 Page 810, Lines 43-44, "...is the same as [of] the new function, except [of] the function name".
Should this be: "...is the same as the new function, except for the function name."

**Comment by wesbland** [comment]
@RolfRabenseifner I'm having a hard time tracking the discussion here since it seems to have moved to another issue. Is this one still needed or is everything done in #405 ?

**Comment by schulzm** [comment]
Re: p773 40: "The following return class ..." --> "The following error class ..."

This seems to have been fixed in the PDF provided by @RolfRabenseifner (but I am not sure who introduced it, @RolfRabenseifner or @mahermanns, do you know?), but I don't think this change is right. When we wrote the MPI_T interface, we decided to handle returns differently and hence named the returns "return codes" - see intro of MPI_T and large table at the end of Chapter 15. 

We may want to revisit this now that we can have MPI error handling before Init, but for MPI 4.0 I would leave return code

**Comment by schulzm** [comment]
@jsquyres @RolfRabenseifner Regaring Jeff's comment:  p772 11: It's a little confusing to mention the removed interfaces in the Deprecated chapter. Why is that mentioned here? (removal of the C++ bindings is already described in chapter 17)

I understand Rolf's comment on why this is where it is, but I also find it a bit odd - especially after the discussion last time that the MPI standard should represent the current state of things and not history, I wonder if we should remove such statements - for the C++ bindings that would mean they would only show up in the deleted chapter and no where else. This is probably too much surgery for MPI 4.0, but could be a goal for 4.1. Thoughts?

**Comment by schulzm** [comment]
@jsquyres @RolfRabenseifner We discussed this at the virtual meeting on Jan. 8th - consensus was to keep this for now, but such history should likely be taken out as part of 4.1 - we will create a new ticket for this

**Comment by RolfRabenseifner** [comment]
p772 11 (in 16.2 Deprecated since MPI-2.2) is already resolved. 

The old text was
> The entire set of C++ language bindings have been removed. See Chapter 17, Removed
Interfaces for more information.

The new text is:
> The entire set of C++ language bindings was deprecated as of MPI-2.2 and removed in
MPI-3.0. See Chapter 17, Removed Interfaces for more information.

**Comment by RolfRabenseifner** [comment]
The two remaining items on page 770 (810 of 1121) are now filed in https://github.com/mpi-forum/mpi-standard/pull/498 and asked there for approval. It is also listed in my summary Issue #405.

**Comment by RolfRabenseifner** [comment]
See also pages 778-779 (818-819 of 1132) in [mpi40-report_Issue405_PR498_v01.pdf](https://github.com/mpi-forum/mpi-issues/files/5819790/mpi40-report_Issue405_PR498_v01.pdf)

**Comment by RolfRabenseifner** [comment]
Done, see Issue #405 and merged PR498 mpi-forum/mpi-standard#498
