### ISSUE TITLE
Tools chapter problem: missing events function names in lists (4.0 RC review)

### ISSUE THREAD

**Issue by jsquyres** [mpi-forum/mpi-issues#370]
In discussion with @mahermanns, we concluded that this issue is a definite problem -- more than a minor word smith that you're looking for in a RC review -- so it probably warrants its own issue.

On p766 19-25, there's several lists of MPI_T function names.  The new MPI_T events functions are missing from these lists and need to be added.

**Comment by mahermanns** [comment]
@jsquyres @wesbland @schulzm We just discussed this in the WG call and came to the following conclusion:
1. During my discussion with @jsquyres I totally overlooked that we actually did add a new function `MPI_T_category_get_num_events` that provides the desired number of events in the category. So the current interface is not underspecified as we initially thought and we don't need a special handling here (and the problem is not as big as we thought on Tuesday)
2. The missing mentions should be added (I'll prepare a PR for that) but shouldn't be mission critical.

Would you agree?

**Comment by jsquyres** [comment]
I think that this PR is mainly about your 2nd bullet (the missing mentions).
