### ISSUE TITLE
Update topology examples 8.8 and 8.10

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#412]
# Problem

Example: page 412, code for MPI_NEIGHBOR_ALLGATHER

The code is supposed to be binding, but is pseudo code. How should this be handled? Should the code be complete and runnable? How to distinguish this from examples?

# Proposal

tbd

# Changes to the Text

tbd

# Impact on Implementations

tbd

# Impact on Users

tbd

# References

Insert any internal (other issues) or external (websites, papers, etc.) references here.

**Comment by wgropp** [comment]
This is also inconsistent with the pseudo code for other collective operations. We do need to decide on a consistent style for these - and I think the pseudo code used elsewhere, instead of almost-C, is the appropriate approach.

**Comment by RolfRabenseifner** [comment]
This is already treated in issue #393. 
The mentioned page 412 is now MPI_4.0 page 419.
This type of documenting the definition of the neighbor procedures for graph topologies is needed to show the used buffer locations. Therefore it is not an example (as also mentioned in issue #393.)
I expect that Fortran programmer are able to translate the byte adressing that is here used for C.
I expect that C programmers are also able to translate it to their definition of sendbuf and recvbuf.
Therefore, I would not spend more time on this and I would recommend to close this issue.

**Comment by wgropp** [comment]
I disagree - this has not been dealt with.  The indicated examples are in no known computer language. The options are:

1. Pick one of C or (some dialect of) Fortran
2. Define a language-neutral form, add a definition for lstlisting to mpi-user-macs, and use that consistently.

I'm leaning towards 2, but would be ok with 1 (especially if the choice is C, since there is only one dialect used in the MPI standard).

**Comment by RolfRabenseifner** [comment]
Okay, I'll provide a PR.

**Comment by RolfRabenseifner** [comment]
@wgropp Dear Bill, my apologies, but I do not see what's wrong with MPI-4.0 page 419, lines 6-21? For me, it seems to be correct C code. The same seems for me to be true with all other MPI_Neigbor_ALL... procedures. 
And I also do not see a bug in the C code of Example 8.10 on page 424.
Or do you mean some other code? Best regards, Rolf

**Comment by wgropp** [comment]
See Example 8.8, page 414, lines 27 and 31. The code "MPI_Cart_sub(comm, remain_dims, newcomm)" isn't C - newcomm isn't an address(no & in front) and there is no semicolon at the end.  It isn't Fortran - there is no call. It isn't language neutral - the routine name is in mixed case. What is it?

There are many such occurrences in the standard.

The example at 419, lines 6-21 is ok and is in a lstlisting in 4.1 draft.  The Example 8.10 I think may be correct but only if it is understood that sendbuf is an array of pointers, rather than an array of values, which is not made explicit in the description. If sendbuf is an array of values, then it is not correct. If sendbuf is an array of pointers, I recommend changing the name to make that clear.

**Comment by RolfRabenseifner** [comment]
In Example 8.8 (was already there in MPI-1.1) I would keep the description of the remain_dims array values and substitute
> MPI_Cart_sub(comm, remain_dims, newcomm)

by 
> MPI_Cart_sub(comm, remain_dims, &newcomm);

In Exa 8.10, I would add 
> MPI_Type_get_extent(sendtype, &send_lb, &send_extent); MPI_Type_get_extent(recvtype, &recv_lb, &recv_extent);

and substitute
> sendbuf[xxx]

by
> sendbuf+(xxx)\*send_count\*send_extent

and same for recvbuf. 
Correct?

**Comment by wgropp** [comment]
The bigger question that I was bringing up was the choice between picking a particular language binding for these "as if" code fragments or using a precisely defined language-neutral version. If we pick a particular language binding, I think it should be the same language everywhere, and that should be C.

**Comment by wgropp** [comment]
On the send buf, it could instead be
`float *sendbufptr[6]; ` and then the code would work as written - but this would need to be described. Your change also works, and wouldn't require any change to the text.

**Comment by wesbland** [comment]
I agree that this is a chapter committee change and we can merge it without a reading.

**Comment by RolfRabenseifner** [comment]
PDF file: [mpi41-report_Issue412_PR743.pdf](https://github.com/mpi-forum/mpi-standard/files/10023828/mpi41-report_Issue412_PR743.pdf)

**Comment by RolfRabenseifner** [comment]
Reading is only scheduled for the case that this issue is not approved by the chapter committee and merged before the Dec. 2022 meeting (as fallback).

**Comment by RolfRabenseifner** [comment]
**@ chapter committee**:  @GuillaumeMercier @cblaas @htorst @tonyskjellum, @ Mahdieh Ghazimirsaeed, @cniethammer : 
**Please reply** whether you approve this issue (yes/no/abstain).

**Comment by tonyskjellum** [comment]
@RolfRabenseifner I approve.

**Comment by wesbland** [comment]
Bill, Guillaume, and I have already approved the PR.

**Comment by RolfRabenseifner** [comment]
chapter committee vote:
- 5x Yes: Bill, Guillaume, and Wes, Tony, myself (Rolf)
- 3x no answer: Christoph, Claudia and Torsten
- 1x vote-request could not be delivered: Mahdieh Ghazimirsaeed

@wesbland I would recommend to take this as a positive chapter committee vote and therefore to merge it.
