### ISSUE TITLE
Fix to the Partitioned Communication Chapter for the rank/process/group/file/win/communicator nomenclature

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#446]
# Problem

Terminology requires that "rank" and "process rank" and "task" be eliminated in favor of new, canonical nomenclature that always scopes the process to have a rank w.r.t. a group of a communicator, group, or underlying group of a file, window, or communicator.

# Proposal

The Forum agrees the nomenclature must be updated as proposed.

# Changes to the Text

Naming of processes is always with regard to ranks related to the underlying object, not as an absolute.

# Impact on Implementations

None.

# Impact on Users

The user community gets better nomenclature and the standard improves considerably.

# References and Pull Requests

PR: [#582](https://github.com/mpi-forum/mpi-standard/pull/582)

**Comment by tonyskjellum** [comment]
[mpi40-report-c29e534-23feb21.pdf](https://github.com/mpi-forum/mpi-issues/files/6030359/mpi40-report-c29e534-23feb21.pdf)

Additional formatting may be needed for overfull lines.

**Comment by wesbland** [comment]
As we discussed in the virtual meeting today, even though this is tackling the process/rank debate, it's very limited in scope and is only touching the new text to avoid getting it wrong the first time. Therefore, having it in 4.0 is ok.

All of that is pending seeing the final PR though since the current one is a bit of a mess. 😄

**Comment by regrant** [comment]
@wesbland the new pull request is up on the ticket, [PR #582](https://github.com/mpi-forum/mpi-standard/pull/582).
