### ISSUE TITLE
Fix Incorrect Usage of Rank/Task/etc. in Tools Chapter

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#481]
# Problem

Replace the incorrect usage of the words "rank", "task", etc. to be correctly specified and reflective of the underlying group, communicator, file, or window.

# Proposal

Read through the entire chapter to find all problematic instances and correct them.

# Changes to the Text

There is unlikely to be a one-size-fits-all solution so the chapter committee will need to consider each occurrence.

# Impact on Implementations

None

# Impact on Users

We will hopefully begin the process of avoiding the incorrect terminology of referring to processes as ranks and other incorrect usages.

# References and Pull Requests

There was a catch-all issue to correct this in https://github.com/mpi-forum/mpi-issues/issues/455, but this is being divided up to cover all chapters.

**Comment by mahermanns** [comment]
@wesbland The tools chapter does not contain any reference to *rank* or *task*. I checked the occurrences of *process*, but those also seem to be OK since our last pass in context of the "connected \MPI/ processes".  So I propose to close this issue. @kathrynmohror @schulzm Do you have any objections?

**Comment by schulzm** [comment]
Sounds reasonable and also not unexpected, as all tool interfaces are local - did a cursory check as well and looks good to me - thanks
