### ISSUE TITLE
C Binding for MPI_CREATE_INFO_ENV

### ISSUE THREAD

**Issue by raffenet** [mpi-forum/mpi-issues#510]
# Problem

As pointed out by a user in pmodels/mpich#5399, the C function signature for MPI_INFO_CREATE_ENV is:
```c
int MPI_Info_create_env(int argc, char argv[], MPI_Info *info)
```
The `argv` argument does not match the ISO C `main` signature.

# Proposal

Change C binding for MPI_CREATE_INFO_ENV to be:
```c
int MPI_Info_create_env(int argc, char *argv[], MPI_Info *info)
```
# Changes to the Text

Binding update.

# Impact on Implementations

Minor (if any) change to code handling `argv` argument.

# Impact on Users

None?

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/609

**Comment by wesbland** [comment]
Yikes! Obviously there was a bug here when I did the Pythonization. The early versions of this function in https://github.com/mpi-forum/mpi-standard/pull/126 had a triple pointer (pass the regular double pointer by reference).

This should be an errata to fix MPI 4.0 to be as suggested above.

**Comment by schulzm** [comment]
I agree, this definitely looks like an errata - however, since this came up I have a slight suspicion/remembrance in the back of my head that we talked about this and did this for a reason, but I cannot find the discussion anymore nor remember the reason. Does anyone remember anything? If not, I think the errata definitely makes sense.

**Comment by wesbland** [comment]
> I agree, this definitely looks like an errata - however, since this came up I have a slight suspicion/remembrance in the back of my head that we talked about this and did this for a reason, but I cannot find the discussion anymore nor remember the reason. Does anyone remember anything? If not, I think the errata definitely makes sense.

I went back through the history of commits in the original PR.  We went from `char ***argv` to `char *argv[]` because we originally were intending to allow MPI to modify the argv list. In the end, we decided not to do that. I think the change to be just `char argv[]` was unintentional (at least it only happens when moving from manual bindings to pythonization) because I didn't realize that the non-pointer version of the `ARGUMENT_LIST` type did not include the `*`.

**Comment by wesbland** [comment]
This passed an errata vote on 2021-09-10:

<table>
<tr>
	<td> Yes </td>
	<td> No </td>
	<td> Abstain </td>
<tr>
	<td> 29 </td>
	<td> 0 </td>
	<td> 1 </td>
</table>
