### ISSUE TITLE
Race condition between MPI_Comm_[i]dup_with_info et al and changes to info and cached values (keyvals) arguments

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#54]
# Problem

There evidently is no text that warns the user that changing info arguments of a parent communicator during the duplication of a communicator with attributes creates a race condition... You could get or not get the new attributes.  In particular, it is not stated if MPI should do anything special.
# Proposal

Define: It is erroneous to change attributes while a MPI_COMM_DUP/IDUP or equivalent operation that duplicates attributes is active.  It is erroneous to change the keyvals of a comm while a DUP/IDUP or equivalent operation is active.

We have to enumerate all such functions impacted by this clarification.
# Changes to the Text

It is erroneous to change attributes while a MPI_COMM_DUP/IDUP or equivalent operation that duplicates attributes is active.  It is erroneous to change the keyvals of a comm while a DUP/IDUP or equivalent operation is active.
# Impact on Implementations

None.
# Impact on Users

Users have to avoid these race conditions now; we are specifically informing them of this need to do so from now on... and by making this an erroneous program, vs. an unsafe program, we make no promises at all.  That means it could raise an error on some implementations too.
# References

**Comment by wgropp** [comment]
The issue with MPI_Comm_dup is already covered by the text on threads, which makes it clear that avoiding such races is the responsibility of the user.  However, these are undefined, not erroneous.  Given our experience with RMA operations, undefined seems fine.

idup raises a different issue, since a single threaded program could still have problems.  And there are other cases; e.g., an Irecv with a communicator that then has an info or attributed changed on it.  What happens?  The cleanest for the user is probably values when the routine is called.  But that has implementation implications, so undefined behavior if changes made probably best

Bill

William Gropp
Director, Parallel Computing Institute
Thomas M. Siebel Chair in Computer Science
Chief Scientist, NCSA
University of Illinois Urbana-Champaign

**Comment by tonyskjellum** [comment]
So we can close the ticket 

Anthony Skjellum, PhD
205-807-4968

**Comment by tonyskjellum** [comment]
Bill, this is a fine point, but what was worrying me when I wrote this
ticket a few minutes ago.

It occurs to me that it is undefined, then any keyval add or delete has to
happen atomically inside the MPI object; when you are multithreaded, you
expect to lock the comm, so no problem.  But, when there is an IDUP in the
same thread asa change, then regardless of the thread level, this race can
happen.  But, MPI would not necessarily want to be locking objects in
single threaded or funneled modes... so wouldn't you prefer to make it
erroneous and not undefined?  What do you think of that case?

Also, it is good that you pointed out where the text is; Dan was not aware
either.  So this was very helpful.

Tony


On Wed, Jun 8, 2016 at 7:22 PM, Tony Skjellum <skjellum@gmail.com> wrote:

> So we can close the ticket
>
> Anthony Skjellum, PhD
> 205-807-4968
>
>
> On Jun 8, 2016, at 5:13 PM, William Gropp <notifications@github.com>
> wrote:
>
> The issue with MPI_Comm_dup is already covered by the text on threads,
> which makes it clear that avoiding such races is the responsibility of the
> user. However, these are undefined, not erroneous. Given our experience
> with RMA operations, undefined seems fine.
>
> idup raises a different issue, since a single threaded program could still
> have problems. And there are other cases; e.g., an Irecv with a
> communicator that then has an info or attributed changed on it. What
> happens? The cleanest for the user is probably values when the routine is
> called. But that has implementation implications, so undefined behavior if
> changes made probably best
>
> Bill
>
> William Gropp
> Director, Parallel Computing Institute
> Thomas M. Siebel Chair in Computer Science
> Chief Scientist, NCSA
> University of Illinois Urbana-Champaign
>
>
>
>
>
> On Jun 8, 2016, at 6:52 PM, Tony Skjellum <notifications@github.com>
> wrote:
>
> > Problem
> >
> > There evidently is no text that warns the user that changing info
> arguments of a parent communicator during the duplication of a communicator
> with attributes creates a race condition... You could get or not get the
> new attributes. In particular, it is not stated if MPI should do anything
> special.
> >
> > Proposal
> >
> > Define: It is erroneous to change attributes while a MPI_COMM_DUP/IDUP
> or equivalent operation that duplicates attributes is active. It is
> erroneous to change the keyvals of a comm while a DUP/IDUP or equivalent
> operation is active.
> >
> > We have to enumerate all such functions impacted by this clarification.
> >
> > Changes to the Text
> >
> > It is erroneous to change attributes while a MPI_COMM_DUP/IDUP or
> equivalent operation that duplicates attributes is active. It is erroneous
> to change the keyvals of a comm while a DUP/IDUP or equivalent operation is
> active.
> >
> > Impact on Implementations
> >
> > None.
> >
> > Impact on Users
> >
> > Users have to avoid these race conditions now; we are specifically
> informing them of this need to do so from now on... and by making this an
> erroneous program, vs. an unsafe program, we make no promises at all. That
> means it could raise an error on some implementations too.
> >
> > References
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mpi-forum/mpi-issues/issues/54#issuecomment-224768682>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA38iVcfOtRpP3EJfLIas223HwVekNQwks5qJ1qMgaJpZM4IxhG6>
> .
>
>


-- 
Anthony Skjellum, PhD
skjellum@gmail.com
Cell: +1-205-807-4968

**Comment by wgropp** [comment]
I agree that this is the issue; we don’t want to require the implementation to thread-serialize all operations that might impact this.

We already have the problem of undefined vs. erroneous elsewhere in the standard - the intent of the text on threads was to allow the implementation to ignore the need for locks/critical sections/other serialization.  Of course, if the user ignores this, the MPI implementation may not execute correctly, since the races may corrupt the internal data structures beyond repair.

The reason that I want to avoid mandating that it is erroneous is that this gives the impression that MPI can/should detect and report the error, which is also not the intent.  It might be best to address this by slightly strengthening the text about thread safety (undefined behavior can mean that the MPI implementation will suffer from an internal race) and adding something to the terms chapter on nonblocking operations and changing the arguments/objects used as input to those non-blocking routines (which would include buffers, MPI objects)

Bill

William Gropp
Director, Parallel Computing Institute
Thomas M. Siebel Chair in Computer Science
Chief Scientist, NCSA
University of Illinois Urbana-Champaign

**Comment by schulzm** [comment]
Based on the discussions, this can be closed
