### ISSUE TITLE
what does 'equivalent to Fortran' mean

### ISSUE THREAD

**Issue by jeffhammond** [mpi-forum/mpi-issues#560]
# Problem

Regarding MPI 4.0 page 869, the following seem to be missing a word:

"C type: MPI_Fint*                  equivalent to Fortran"
"C type: MPI_F08_status*            equivalent to Fortran"

I know for a fact that MPI_Fint and MPI_F08_status are, by themselves, not equivalent to Fortran.

<img width="712" alt="Screen Shot 2022-07-19 at 8 15 49 PM" src="https://user-images.githubusercontent.com/406118/179889001-c02a4e3f-acca-4089-90a1-e9e190446e19.png">

# Proposal

Say the thing in Fortran that is actually actually equivalent to MPI_Fint and MPI_F08_status.

# Changes to the Text

TBD

# Impact on Implementations

Implementaters will be less confused when reading the spec.

# Impact on Users

Users will be less confused when reading the spec.

# References and Pull Requests

[PR 713](https://github.com/mpi-forum/mpi-standard/pull/713)

**Comment by jeffhammond** [comment]
@RolfRabenseifner This is an erratum, right?

**Comment by RolfRabenseifner** [comment]
> @RolfRabenseifner This is an erratum, right?

I expect that the text on MPI-4.0 pages 844 and 845 clearly tells to implementors and users the meaning of these constants.
But I understand your problem with this table.

Do you want to change the text "equivalent to Fortran" into 
- "equivalent to Fortran constants:"

or
- "Equivalent to Fortran constants:"

that it gets absolutely clear that this column header is the column header of the two values below, rather than being a some continuation of the wording  "C type: MPI_Fint*" and "C type: MPI_F08_status*"?

**Comment by RolfRabenseifner** [comment]
@jeffhammond Which correction would you prefer? One of the two corrections proposed above, or a third one?

**Comment by bkmgit** [comment]
There have been related complications in implementations:

- https://github.com/open-mpi/ompi/issues/76
- https://github.com/pmodels/mpich/pull/5057

**Comment by jeffhammond** [comment]
@RolfRabenseifner "equivalent in Fortran" seems like the smallest correct change

**Comment by bkmgit** [comment]
Another related issue https://github.com/open-mpi/ompi/issues/7918

[OpenMPI](https://github.com/open-mpi/ompi/blob/main/ompi/include/mpi.h.in#L235) `MPI_Fint is the same as ompi_fortran_INTEGER_t`
[Check sizes during configuration of OpenMPI](https://github.com/open-mpi/ompi/blob/main/config/ompi_fortran_get_sizeof.m4#L31)

[MPICH](https://github.com/pmodels/mpich/blob/main/src/include/mpi.h.in#L563) `Definitions that are determined by configure`

In both cases, the type is the default Fortran integer type specified when compiling the library. Programs using the compiled library need to use the same default Fortran integer type. 

Maybe "equivalent Fortran constant" is better?

**Comment by bkmgit** [comment]
@jeffhammond @RolfRabenseifner Feedback appreciated

**Comment by RolfRabenseifner** [comment]
Yes, I also needed some time to fully understand what this table should say.

I would recommend to substitute
> C type: MPI_Fint*    ___________    equivalent to Fortran

by
> C constant (type: MPI_Fint*) ______ is equivalent to the Fortran constant

**Comment by RolfRabenseifner** [comment]
@jeffhammond and @bkmgit  Do you both like my proposal above in https://github.com/mpi-forum/mpi-issues/issues/560#issuecomment-1285704454? Should I proceed with a PR for that?

**Comment by bkmgit** [comment]
@RolfRabenseifner That seems fine for me. Happy to update the pull request to learn the workflow.  @jeffhammond thoughts on this?

**Comment by bkmgit** [comment]
Updated pull request to use:
```
C constant type: MPI_Fint*  ______ equivalent Fortran constant type
```
Maybe this is clearer? Could also use
```
C constant type: MPI_Fint*  ______ equivalent constant type in Fortran
```

**Comment by RolfRabenseifner** [comment]
No, because the left and the right column present constants.
The table only shows the definition of the constants in the left column that must be provided within mpi.h.
These constants can be used to be passed from C to Fortran where they can be used instead of the constants in the right column.
Therefore, these C constants have very special types: 
- MPI_Fint* to be passed from C to Fortran and used there for Fortran calls defined in mpif.h or the mpi module.
- MPI_F08_status*, the same but within the mpi_f08 module.

The normal constants used in C to be passed to the MPI routine in C and in Fortran to be passed to the MPI routine in Fortran, they are shown in the table before, i.e. Table "Constants Specifying Empty or Ignored Input" on mPI-4.0 page 868.

Therefore, I recommend to use the headers

`C constant (type: MPI_Fint*) ______ is equivalent to the Fortran constant`

and

`C constant (type: MPI_F08_status*) ______ is equivalent to the Fortran constant`

Note that this summary does not substitute the detailed information in MPI-4.0 Section 19.3.5 Status.

If you agree, then I would provide a PR with this change.

**Comment by RolfRabenseifner** [comment]
@jeffhammond As soon as you give an **okay** per review on [PR 713](https://github.com/mpi-forum/mpi-standard/pull/713)
and page 827 of [mpi41-report_Issue560_PR713.pdf](https://github.com/mpi-forum/mpi-standard/files/10023611/mpi41-report_Issue560_PR713.pdf),
I'll ask for merging of this PR.

**Comment by RolfRabenseifner** [comment]
**@ chapter committee**:  @puribangalore @tonyskjellum @hritzdorf  : 
**Please reply** whether you approve this issue (yes/no/abstain).

**Comment by tonyskjellum** [comment]
@RolfRabenseifner I give the plus vote.

**Comment by RolfRabenseifner** [comment]
Also approved by me. 

@wesbland Result: 3x approved, 1x not here (Hubert is not on this MPI Forum meeting). I would say you can set it to approved by the chapter committee and therefore pass it to @wgropp for merge.
