### ISSUE TITLE
Terms - Code Examples Marked Improperly

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#591]
# Problem

Code examples should be marked so that the code checker can confirm that they at least compile - the information on this is in the instructions, and there are a zillion example in the document. The code checker has found many problems and helps ensure a higher quality document. I noted problems in binding-2.tex, but will need to review all of the other examples now.
In that chapter, many examples are marked with `%%SKIP` when they should be properly marked for the language etc.

# Proposal

Follow the instructions in `instr.tex/pdf`. If there are problems or questions, contact @wgropp.

# Changes to the Text

No changes to the text.  The code checker uses structured comments.

# Impact on Implementations

None.

# Impact on Users

Improved quality of the document.

# References

This is covered in instr.pdf.

### Instructions

If there is nothing to do in your chapter, just comment and close this issue. Otherwise, create a PR to address the problems.

**Comment by wesbland** [comment]
This wasn't read at the December 2022 meeting. The last opportunity for MPI 4.1 is to have it ready at the March 2022 meeting (and it needs to "pass" the reading).

@cblaas Are you (or is someone else) planning to push this forward or should we move it out of the plan for MPI 4.1?

**Comment by RolfRabenseifner** [comment]
Based on following details, I would close this issue, but I'm only 90% sure with my expectation about the Fortran code checker.

Page numbers in official MPI-4.0, and line numbers in current
https://github.com/mpi-forum/mpi-standard/blob/mpi-4.x/chap-terms/terms-2.tex

There  is only one %%SKIP:

Page 18:
TYPE, BIND(C) :: MPI_Comm
  INTEGER :: MPI_VAL
END TYPE MPI_Comm

with terms-2.tex lines 566-574
%%HEADER
%%LANG: FORTRAN08
%%SKIP
%%ENDHEADER
\begin{lstlisting}[language={[MPI08]Fortran}]
TYPE, BIND(C) :: MPI_Comm
  INTEGER   :: MPI_VAL
END TYPE MPI_Comm
\end{lstlisting}


I expect, that the %%SKIP is chosen because this code is part of 
the mpi and mpi_f08 module, and not of a normal user application.
I expect that the checker is not prepared for this.


All other locations seem to be correct:

page numbers in official MPI-4.0, and line numbers in current
https://github.com/mpi-forum/mpi-standard/blob/mpi-4.x/chap-terms/terms-2.tex

page 12: void copyIntBuffer
lines 144-152 with %%HEADER...

page 13: int a[10];
lines 154-162 with %%HEADER...

page 28: int commworld_rank;
lines 1427-1437 with %%HEADER...

page 28 again: MPI_Comm_rank(MPI_COMM_WORLD, &commworld_rank);
lines 1446-1455 with %%HEADER...

**Comment by cblaas** [comment]
I fully agree with @RolfRabenseifner and think there is nothing to be improved in the Terms Chapter.

All C codes and code fragments seem to be already marked correctly for the code checker.

There is only a single occurrence of %%SKIP together with showing one example of how the handles are defined in the Fortran mpi and mpi_f08 modules itself. Lines like these will never go into a normal user application, I doubt the code checker is prepared for this, and I'm quite sure there is no benefit from checking lines like these anyway.

If @RolfRabenseifner and @wgropp agree, I suggest to close this issue with "Nothing to be done in the Terms Chapter."
