### ISSUE TITLE
Topology - use of \MPI process where necessary 

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#649]
# Problem

Address use of `\MPI process(es)` where necessary in the topology chapter

# Proposal and text changes

See https://github.com/mpi-forum/mpi-standard/pull/764

# Impact on Implementations

None

# Impact on Users

Clarification

# References and Pull Requests

https://github.com/mpi-forum/mpi-standard/pull/764

**Comment by wesbland** [comment]
The scope of the change here makes me a little uncomfortable calling it a CC change. I'd definitely want @schulzm and @wgropp to give it a 👍 first.

**Comment by cniethammer** [comment]
pdf version: [mpi41-report-issue-649-pr-764.pdf](https://github.com/mpi-forum/mpi-issues/files/10167008/mpi41-report-issue-649-pr-764.pdf)
pdf version with highlighted chanches: [mpi41-report-diff-issue-649-pr-764.pdf](https://github.com/mpi-forum/mpi-issues/files/10167009/mpi41-report-diff-issue-649-pr-764.pdf)

**Comment by RolfRabenseifner** [comment]
The issues 649, 650 and 651 are prepared by Christoph and they had an official reading at the December 2022 meeting.
I would prefere to handle them through chpater committee vote because the forum had already seen them and the type of content does not require full forum voting. Therefore:

**@ chapter committee**:  @GuillaumeMercier @cblaas @htorst @tonyskjellum, @ Mahdieh Ghazimirsaeed, @cniethammer : 
**Please reply** whether you approve this issue (yes/no/abstain).

**Comment by GuillaumeMercier** [comment]
> The issues 649, 650 and 651 are prepared by Christoph and they had an official reading at the December 2022 meeting.

@RolfRabenseifner : you mean the PRs, not the issues, right?
I'm ok with the PR that fixes issue #649.

**Comment by RolfRabenseifner** [comment]
I'm ok with the PR that fixes this issue #649.

**Comment by cniethammer** [comment]
I'm ok with the PR that fixes issue #649.

**Comment by cblaas** [comment]
I'm ok with the PR that fixes issue https://github.com/mpi-forum/mpi-issues/issues/649.

**Comment by RolfRabenseifner** [comment]
@wgropp @wesbland Dear Bill and Wesley, the [PR 764](https://github.com/mpi-forum/mpi-standard/pull/764) of this issue was read at the Dec 2022 meeting and it was mentioned that we plan to do it with a chapter committee vote. 
The chapter committee votes were:
- 4x YES (Guillaume, Christoph, Claudia and me)
- 2x no reaction (Torsten and Tony seem to be currently inactive on this CC)
- 1x not reachable (Mahdieh) 

Additionally on the PR764, @wgropp wrote
> I'm going to make the same comment I've made for many of these such changes - I'd prefer to say that "process" means "MPI process" unless otherwise specified. There is almost no place in the standard where process means something else. However, this change isn't wrong, but I don't think it adds much.

@wgropp and @wesbland I would recommend to take this all as a positive chapter committee vote and therefore to merge it.
