### ISSUE TITLE
Topology improvement around the term virtual topology

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#650]
# Problem

The topology chapter is not consistent in the use of 'virtual topology'

# Proposal

Make consistent use of 'virtual topology'

# Changes to the Text
See https://github.com/mpi-forum/mpi-standard/pull/765

# Impact on Implementations

None

# Impact on Users

Clarification

# References and Pull Requests
https://github.com/mpi-forum/mpi-standard/pull/765

**Comment by cniethammer** [comment]
pdf version: [mpi41-report.pdf](https://github.com/mpi-forum/mpi-issues/files/10166620/mpi41-report.pdf)

pdf version with highlighted changes: [mpi-report-diff-ticket-650.pdf](https://github.com/mpi-forum/mpi-issues/files/10166613/mpi-report-diff-ticket-650.pdf)

**Comment by RolfRabenseifner** [comment]
The issues 649, 650 and 651 are prepared by Christoph and they had an official reading at the December 2022 meeting. 
I would prefere to handle them through chpater committee vote because the forum had already seen them and the type of content does not require full forum voting. Therefore:

**@ chapter committee**:  @GuillaumeMercier @cblaas @htorst @tonyskjellum, @ Mahdieh Ghazimirsaeed, @cniethammer : 
**Please reply** whether you approve this issue (yes/no/abstain).

**Comment by GuillaumeMercier** [comment]
I'm mostly OK with the PR that fixes issue #650, but I made a suggestion, though.

**Comment by RolfRabenseifner** [comment]
I'm okay with the PR (including Guillaume's fix) that fixes this issue #650.

**Comment by cniethammer** [comment]
Updated PR fixing issue #650 with the requested two minor whitespace/wording changes. OK from my side.

**Comment by cblaas** [comment]
I'm okay with the PR that fixes this issue https://github.com/mpi-forum/mpi-issues/issues/650.

**Comment by RolfRabenseifner** [comment]
@wgropp @wesbland Dear Bill and Wesley, the [PR 765](https://github.com/mpi-forum/mpi-standard/pull/765) of this issue was read at the Dec 2022 meeting and it was mentioned that we plan to do it with a chapter committee vote. 
The chapter committee votes were:
- 4x YES (Guillaume, Christoph, Claudia and me)
- 2x no reaction (Torsten and Tony seem to be currently inactive on this CC)
- 1x not reachable (Mahdieh) 

Additionally on the PR765, @wgropp wrote
> As I've noted in other places, I'd prefer not to add such qualifiers when they are used in almost every occurrence. I'd rather qualify the exceptions. But this is not wrong and does not change the meaning of the text, so I'm ok with it as a CC.

@wgropp and @wesbland I would recommend to take this all as a positive chapter committee vote and therefore to merge it.
