### ISSUE TITLE
Topology typos and smaller text improvements

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#651]
# Problem

Some typos and smaller text issues in the topology chapter should be fixed

# Changes to the Text

See https://github.com/mpi-forum/mpi-standard/pull/744

# Impact on Implementations

None

# Impact on Users

None

# References and Pull Requests

See https://github.com/mpi-forum/mpi-standard/pull/744

**Comment by cniethammer** [comment]
pdf version: [mpi41-report-issue-651-pr-744.pdf](https://github.com/mpi-forum/mpi-issues/files/10166909/mpi41-report-issue-651-pr-744.pdf)
pdf version with highlighted changes: [mpi41-report-diff-issue-651-pr-744.pdf](https://github.com/mpi-forum/mpi-issues/files/10166911/mpi41-report-diff-issue-651-pr-744.pdf)

**Comment by RolfRabenseifner** [comment]
The issues 649, 650 and 651 are prepared by Christoph and they had an official reading at the December 2022 meeting.
I would prefere to handle them through chpater committee vote because the forum had already seen them and the type of content does not require full forum voting. Therefore:

**@ chapter committee**:  @GuillaumeMercier @cblaas @htorst @tonyskjellum, @ Mahdieh Ghazimirsaeed, @cniethammer : 
**Please reply** whether you approve this issue (yes/no/abstain).

**Comment by GuillaumeMercier** [comment]
I'm ok with the PR that fixes issue #651.

**Comment by RolfRabenseifner** [comment]
I'm also ok with th PR that fixes this issue #651 (besides only one small recommendation for not removing a comment line).

**Comment by cniethammer** [comment]
I'm ok with the PR that fixes issue #651. (Including the removal of the example reference in the comment  as it is incorrect and will require manual updating. We have example titles making it easy to find examples now.)

**Comment by cblaas** [comment]
I'm ok with the PR that fixes issue https://github.com/mpi-forum/mpi-issues/issues/651.

**Comment by RolfRabenseifner** [comment]
@wgropp @wesbland Dear Bill and Wesley, the [PR 744](https://github.com/mpi-forum/mpi-standard/pull/744) of this issue was read at the Dec 2022 meeting and it was mentioned that we plan to do it with a chapter committee vote. 
The chapter committee votes were:
- 4x YES (Guillaume, Christoph, Claudia and me)
- 2x no reaction (Torsten and Tony seem to be currently inactive on this CC)
- 1x not reachable (Mahdieh) 

On the PR744, there seems to be an outdated issue from a review of @wgropp. I expect that it is resolved. Therefore:

@wgropp and @wesbland I would recommend to take this as a positive chapter committee vote and therefore to merge it.
