### ISSUE TITLE
Make automatic buffering for BSend the default

### ISSUE THREAD

**Issue by schulzm** [mpi-forum/mpi-issues#684]
# Problem

Issue [https://github.com/mpi-forum/mpi-issues/issues/586](https://github.com/mpi-forum/mpi-issues/issues/586 ) adds automatic buffering, but does not make it default.

# Proposal

Add on to [https://github.com/mpi-forum/mpi-issues/issues/586](https://github.com/mpi-forum/mpi-issues/issues/586) to make this automatic

# Changes to the Text

Changing the default

# Impact on Implementations

Minimal, only default changes

# Impact on Users

Easier usage of automatic buffered mode send, but possibly forward incompatibility.

# References and Pull Requests

tbd.

**Comment by abouteiller** [comment]
Text as proposed in PR [#807](https://github.com/mpi-forum/mpi-standard/pull/807) would cause existing MPI-3 programs to become erroneous because they call BUFFER_ATTACH before calling BUFFER_DETACH to disable the default. 

We regarded this as a fatal flow for this proposal, and this idea will be shelved until MPI-5 where a new champion may try a different, more backward compatible approach.

**Comment by schulzm** [comment]
At the March 2023 meeting the forum decided to no longer pursue this
