### ISSUE TITLE
Cant install mpi4y on python 3.10

### ISSUE THREAD

**Issue by djaym7** [mpi-forum/mpi-issues#689]
Following error : on pip install mpi4py
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `mca_base_var_group_get_count'
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_datatype_resize'
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_hash_table_set_value_uint64'
      /opt/conda/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_list_t_class'
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      error: Cannot link MPI programs. Check your configuration!!!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> mpi4py

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by christgau** [comment]
I can't speak for the MPI forum, but this is hardly an issue related to the MPI standard, i.e. the definition of what it is and what semantics the defined API has. Your issue is most related to mpi4py. Please consider opening an issue, e.g. in the respective [Github repository](https://github.com/mpi4py/mpi4py). There has been [an issue quiet similar to yours](https://github.com/mpi4py/mpi4py/issues/165) to which you may refer or which you may even re-open if versions and the like match.

Note: I was consulted recently with a similar problem, but wasn't able to reproduce the issue. As hinted by the error message, check your configuration and test, e..g, whether the MPI compiler wrapper works as expected.

**Comment by jeffhammond** [comment]
This is the wrong place to report this.
