### ISSUE TITLE
Possible ambiguity on size of `array_of_indices` and `array_of_statuses`?

### ISSUE THREAD

**Issue by AndrewGaspar** [mpi-forum/mpi-issues#86]
Originally posted to mpi-coments forum, but it seems like this is more active based on a glance at the archives. I will change this into a formal proposal if this is indeed an ambiguity in the spec.

---

Hello,
 
These comments are on the MPI 3.1 spec[0], Section 3.7.5, pages 61 and 62 on MPI_Waitsome and MPI_Testsome.
 
The spec makes two comments on what elements in `array_of_indices` and `array_of_statuses` are accessed:
 
“Returns in the first **outcount** locations of the array array_of_indices the indices of these operations (index within the array array_of_requests; the array is indexed from zero in C and from one in Fortran)”
 
“Returns in the first **outcount** locations of the array array_of_status the status for these completed operations.”
 
As far as I can tell, the spec provides no other indication of the size of these two arrays. So, as a user, I would think that `array_of_indices` is only required to be as large as the largest possible value of `outcount`.
 
The max value of outcount is not necessarily the same as the size of `array_of_requests`: If an array_of_requests has 10 elements, but the user knows that only 8 of the requests are active, they know that outcount must be less than or equal to 8.
 
The reason I ask is that OpenMPI takes the liberty of treating `array_of_indices` as being the same size as `array_of_requests`[1]. It uses `array_of_indices[i]` as scratch space to store the completion of `array_of_requests[i]`.
 
Is the spec ambiguous here, or is OpenMPI in violation of the spec? Or am I missing an explicit definition of the required size of these arrays?
 
Thank you very much!
 
[0] http://mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf
[1] https://github.com/open-mpi/ompi/blob/master/ompi/request/req_wait.c#L422

PR: https://github.com/mpi-forum/mpi-standard/pull/42

**Comment by hjelmn** [comment]
Also file a issue on Open MPI. Even if ambiguous in the standard we (Open MPI) might modify the behavior if there is enough agreement between the developments.

**Comment by AndrewGaspar** [comment]
Done!

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@AndrewGaspar personally, I have always assumed that the ```incount``` describes the length of all three arrays passed to the routine, i.e. the usable length for output arrays.

Given that Open MPI also makes this assumption, this should probably be treated as an errata; for example, by adding a statement something like:
> The ```array_of_indices``` and ```array_of_statuses``` must contain at least ```incount``` elements.

Aside: using the array elements between ```outcount``` and ```incount``` as scratch space may surprise a sufficiently alert user. In most other cases, MPI guarantees that padding and surrounding bytes are not accessed by MPI. This suggests that those trailing elements probably should not be accessed at all by MPI, but certainly should not be changed by MPI. There is no indication in the standard about whether this behaviour/guarantee applies. One compromise would be to specify that MPI sets the spare elements of ```array_of_indices``` (up to ```incount```) to ```MPI_UNDEFINED``` and the spare elements of ```array_of_statues``` (up to ```incount```) to empty status. That would permit MPI to use those elements as scratch space during the call as long as it makes sure they are reset to known (invalid) values before it returns. No currently correct program would notice because it would only trust the values in the first ```outcount``` elements.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Unrelated, but can be corrected at the same time:
> Any other type or request that completed is deallocated
should be
> Any other type of request that completed is deallocated
MPI-3.1 p61 line 19

**Comment by schulzm** [comment]
@dholmes-epcc-ed-ac-uk: should this be scheduled for Austin?

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@schulzm Yes, I will add this to my to-do list.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Suggested change, based on MPI-3.x (as of a few moments ago), with change-bars:
[mpi-report-ticket86.pdf](https://github.com/mpi-forum/mpi-issues/files/2026534/mpi-report-ticket86.pdf)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Suggested change, based on MPI-3.x (as of a few moments ago), with change-bars and change log entry:
[mpi-report-ticket86.pdf](https://github.com/mpi-forum/mpi-standard/files/2026613/mpi-report-ticket86.pdf)

**Comment by AndrewGaspar** [comment]
The PDF is 404 for me.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Suggested change, based on MPI-3.x (as of a few moments ago), with change-bars and change log entry:
[mpi-report-ticket86.pdf](https://github.com/mpi-forum/mpi-issues/files/2027396/mpi-report-ticket86.pdf)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@AndrewGaspar Please try again (I attempted to correct the link)

**Comment by AndrewGaspar** [comment]
Hm... why is this this just "array_of_requests" and "array_of_statuses", but doesn't include "array_of_indices"? array_of_indices is treated as parallel to array_of_statuses.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@AndrewGaspar apologies, that's a case of excessive haste. I will adjust the text to include ```array_of_indices```.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Suggested change, with added ```array_of_indices``` goodness:
[mpi-report-ticket86.pdf](https://github.com/mpi-forum/mpi-issues/files/2030446/mpi-report-ticket86.pdf)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Additional changes in response to feedback at June 2018 face-to-face meeting:
[mpi-report-ticket86v2.pdf](https://github.com/mpi-forum/mpi-issues/files/2096418/mpi-report-ticket86v2.pdf)

**Comment by dholmes-epcc-ed-ac-uk** [comment]
the Forum decided that this ambiguity should be resolved in the opposite direction to the way this issue is currently phrased.

Specifically, there is a use-case for defining arrays of equal size for requests, indices, and statuses, then iteratively calling this function (either of MPI_[WAIT|TEST]SOME) with an incremented pointer each time. The pointers for indices and statuses can be incremented by outcount each time to provide to MPI the empty portion of those arrays, which must be large enough for the remaining work by construction. Such an algorithm would check, when incrementing by outcount, whether the entire array had been written.

If this issue had been accepted as currently specified, then to use the approach described above would unnecessarily require the user to allocate a buffers for indices and statuses that were twice the size of requests.

A straw poll at the June face-to-face meeting suggests there is no support for this issue as currently specified, little support for no change to the Standard, and majority support for permitting smaller-than-incount arrays, i.e. clarifying exactly how much smaller is permitted.

**Comment by jeffhammond** [comment]
@dholmes-epcc-ed-ac-uk It took me a bit of thinking to understand what the use case was so, to be pedantic, I wrote the following.  Do I interpret what you've said correctly?

```c
void foo(int n, MPI_Request array_of_requests[n], int array_of_indices[n],
         MPI_Status array_of_statuses[n])
{
  int incount = n;
  int outcount = incount;
  while (incount > 0) {
    int rc = MPI_Waitsome(incount, array_of_requests, &outcount,
                          array_of_indices, array_of_statuses);
    CHECKMPI(rc);
    incount -= outcount;
    array_of_indices += outcount;
    array_of_statuses += outcount;
  }
}
```

**Comment by bosilca** [comment]
You can't decrement the incount, it must remain invariant so that you check all requests in array_of_requests. But this is indeed the idea. A highly unoptimized code at the heart of one of the most performance critical section of an MPI application.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
@jeffhammond apart from the line: ```incount -= outcount``` (which should be removed from your code). It is not known which of the ```n``` requests completed and so the entire ```array_of_requests``` is supplied to the function each time, i.e. ```incount``` remains unchanged. Another stack variable is needed to keep track of the sum of all values of ```outcount``` returned so far, in order to correctly terminate the while loop.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
Perhaps slightly better would be a code that used ```MPI_TESTSOME``` is the same manner and attempted to overlap some other work in between calls. With truly asynchronous progress, poking the progress engine in this manner should not be needed. However, this issue is not about the merits or otherwise of the ```MPI_[TEST|WAIT]SOME``` functions.

**Comment by dholmes-epcc-ed-ac-uk** [comment]
I'm closing this issue (and it's PR) because the originally suggested change is the wrong fix for any ambiguity that exists with the referenced text.
